### ISSUE TITLE
Not being able to open truck inventory with esx_jobs vehicle

### ISSUE THREAD

**Issue by Rhydium** [dutchplayers/FiveM-Resources#100]
Hello,

When I try to open the inventory from the truck provided with esx_jobs it says the vehicle is locked when trying to open the inventory. I need people to be able to open the inventory of trucks provided by esx_jobs so when someone knows how to fix this I would be happy 😛 

_Oh and this is issue #100 🎉_

**Comment by RockySouthpaw** [comment]
I’m assuming you specified in the config that you CANT open the trunk unless you own the vehicle?

If so, this is probably the cause of it. 

If not, what vehicle is it? Have you tried other vehicles such as a futo?

**Comment by RuisSoftware** [comment]
@Rhydium Can you answer @RockySouthpaw

**Comment by Rhydium** [comment]
> I’m assuming you specified in the config that you CANT open the trunk unless you own the vehicle?
> 
> If so, this is probably the cause of it.
> 
> If not, what vehicle is it? Have you tried other vehicles such as a futo?

I have this in my esx_inventoryhud_trunk config.lua:
`Config.CheckOwnership = false -- If true, Only owner of vehicle can store items in trunk.`

**Comment by FBFezz** [comment]
Do you have some sort of lock script that locks your vehicle? Maybe the vehicle is locked when you tried opening it?

**Comment by RockySouthpaw** [comment]
Did you try trunks with vehicles spawned via /car?

**Comment by Rhydium** [comment]
Mkay, so I did some further testing and sometimes it does seem to work and sometimes it doesn't. 
I really don't know what causes this..

**Comment by RockySouthpaw** [comment]
Did you try vehicles that were spawned with /car? Or vehicles that you purchased from the dealership?

**Comment by Rhydium** [comment]
Nope, /car doesn't fix anything.

**Comment by Rhydium** [comment]
Mhm think I just found the issue, when the config is as following it doesn't work:
```
Config.CheckOwnership = false -- If true, Only owner of vehicle can store items in trunk.
Config.AllowPolice = true -- If true, police will be able to search players' trunks.
```

But when I change `Config.AllowPolice` to `false` it does seem to work again.

**Comment by RockySouthpaw** [comment]
Change it to true and restart the resource. See if you get any errors in the f8 console.
