### ISSUE TITLE
Double Item from other player [BUG]

### ISSUE THREAD

**Issue by thefrcrazy** [dutchplayers/FiveM-Resources#101]
Hello when trying to recover an item or money from a player it gives me double asking
![Screenshot_25](https://user-images.githubusercontent.com/37953895/83930831-e01c3000-a799-11ea-9368-4c7976cbe94a.png)
![Screenshot_26](https://user-images.githubusercontent.com/37953895/83930834-e14d5d00-a799-11ea-8e09-071836144377.png)

**Comment by RuisSoftware** [comment]
Should be fixed now.
