### ISSUE TITLE
Issue with legacy fuel jerry can

### ISSUE THREAD

**Issue by AgenChicken24** [dutchplayers/FiveM-Resources#102]
When i am buying jerry can from gas station i have it in the tab menu but in esx_inventory hud i don’t have it. When i am buying jerry can from weapon shop because i have added it i have it in my inventory and in the tab menu from gta 5 and i can fill but when i buy it from gas station nothing pls help if you need to say anything say i will send it ty. Have a nice day.
From AgenChicken.
PS: I have the item in the database. This is the command 
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES 
('WEAPON_PETROLCAN', 'Jerry Can', 1, 0, 1, 0)

**Comment by RockySouthpaw** [comment]
Dont give yourself the weapon with legacy fuel. Give yourself the item.

Line 244 in fuel_client.lua, replace GiveWeaponToPed like so

```
--GiveWeaponToPed(ped, 883325847, 4500, false, true)
TriggerServerEvent('gas:GiveItem')
```

And make a server event for it:

```
RegisterServerEvent("gas:GiveItem") 
AddEventHandler("gas:GiveItem", function()
  	local _source = source
  	local xPlayer = ESX.GetPlayerFromId(_source)
    xPlayer.addInventoryItem('WEAPON_PETROLCAN', 1)
end)
```

Edit: Fixed the name.

**Comment by xluiisx** [comment]
It doesn't work @RockySouthpaw

**Comment by RockySouthpaw** [comment]
@xluiisx 

> It doesn't work @RockySouthpaw


Your item for the gas can is probably different. Do WEAPON_PETROLCAN or whatever it’s called in your database. I’ve updated my post.

**Comment by RuisSoftware** [comment]
> 
> 
> Dont give yourself the weapon with legacy fuel. Give yourself the item.
> 
> Line 244 in fuel_client.lua, replace GiveWeaponToPed like so
> 
> ```
> --GiveWeaponToPed(ped, 883325847, 4500, false, true)
> TriggerServerEvent('gas:GiveItem')
> ```
> 
> And make a server event for it:
> 
> ```
> RegisterServerEvent("gas:GiveItem") 
> AddEventHandler("gas:GiveItem", function()
>   	local _source = source
>   	local xPlayer = ESX.GetPlayerFromId(_source)
>     xPlayer.addInventoryItem('WEAPON_PETROLCAN', 1)
> end)
> ```
> 
> Edit: Fixed the name.

Anyone tested this solution?

**Comment by ghost** [comment]
Edit: It works thanks

**Comment by ninny2104** [comment]
RegisterServerEvent("gas:GiveItem") 
AddEventHandler("gas:GiveItem", function()
  	local _source = source
  	local xPlayer = ESX.GetPlayerFromId(_source)
  xPlayer.addWeapon('WEAPON_PETROLCAN', 4500)
end)

**Comment by RuisSoftware** [comment]
> 
> 
> RegisterServerEvent("gas:GiveItem")
> AddEventHandler("gas:GiveItem", function()
> local _source = source
> local xPlayer = ESX.GetPlayerFromId(_source)
> xPlayer.addWeapon('WEAPON_PETROLCAN', 4500)
> end)

You can't give a weapon, it will not be shown in your inventory. You have to give it as item.

**Comment by xrtw** [comment]
you cant fill a car with this

**Comment by Borea** [comment]
When I throw the item from my inventory, is not dissapearing from my hand. Also, when I disconnect and connect again the item dissapear. Any help?

**Comment by RuisSoftware** [comment]
Use v3

**Comment by Borea** [comment]
Where I can find the V3?

**Comment by RuisSoftware** [comment]
Its the latest master branch update

**Comment by sleepingezy** [comment]
> > Dont give yourself the weapon with legacy fuel. Give yourself the item.
> > Line 244 in fuel_client.lua, replace GiveWeaponToPed like so
> > ```
> > --GiveWeaponToPed(ped, 883325847, 4500, false, true)
> > TriggerServerEvent('gas:GiveItem')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And make a server event for it:
> > ```
> > RegisterServerEvent("gas:GiveItem") 
> > AddEventHandler("gas:GiveItem", function()
> >   	local _source = source
> >   	local xPlayer = ESX.GetPlayerFromId(_source)
> >     xPlayer.addInventoryItem('WEAPON_PETROLCAN', 1)
> > end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Edit: Fixed the name.
> 
> Anyone tested this solution?

Works like a charm. Thanks.
