### ISSUE TITLE
The inventory to big

### ISSUE THREAD

**Issue by NazriGenfil** [dutchplayers/FiveM-Resources#103]
![sdsd](https://user-images.githubusercontent.com/40690481/84427199-b7d77a00-ac4e-11ea-9395-0ae81727fb3e.png)

**Comment by RockySouthpaw** [comment]
What resolution

**Comment by Ortupas** [comment]
seragam polisi indo itu beli dimana kalo ada yg jual seragam2 gitu dimana ya

**Comment by RuisSoftware** [comment]
This is made for 1080pi. 

If you want to make it compatible with smaller devices you can create a pull request
