### ISSUE TITLE
Glovebox & Trunk Inventory behaving unusual

### ISSUE THREAD

**Issue by ThatGuyJacobee** [dutchplayers/FiveM-Resources#105]
**Describe the bug**
Hey there, so I've installed the mysql things and everything that is necessary but I'm getting a strange bug where the glovebox and trunk sometimes don't open. I'll attach a screenshot of an error that I get on server start. I do get the connect ETIMEDOUT errors too, but as I've read around other issues, that's normal. But I do get 2 other errors, one from the glovebox script and one from the trunk script.

**To Reproduce**
Steps to reproduce the behaviour:
I've noticed it usually happens after a server restart. However lets say I try open the inventory, and then restart the resource, it will work again but create a error that the license plate is duplicate, although I think that shouldn't be an issue since it's just re-doing everything in the script.

**ESX version:**
 Latest ESX (v1 final)

**Additional context**
I've tried changing the keybinds, thinking it maybe some other script is doubling with this, but after using two different binds it's still happening to me.

**Followed Wiki**
Yes, I've tried searching for this and followed few possible fixes, such as keybinds like mentioned before. Hope you can help 😄 

This is from server start:
![image](https://user-images.githubusercontent.com/42719082/84556834-5a5e2e80-ad1d-11ea-9449-d67c1fe869b3.png)

This is after I restart the resource, which allows me to open either again:
![image](https://user-images.githubusercontent.com/42719082/84556778-cc824380-ad1c-11ea-8c03-008246e08700.png)

**Comment by RuisSoftware** [comment]
Hi, this issue is related to your database. 

What system are you running?

**Comment by ThatGuyJacobee** [comment]
Hey thanks for the quick reply :)
I'm using a dedicated server to host my Five M server as well as my database from Zap Hosting.
My specs on it are:
8gb ram, 6vpu cores and 240gb ssd storage. Bandwith is 100mbit/s up/down.

Edit: Also, my cpu/ram usage is usually less than 75%.

**Comment by ThatGuyJacobee** [comment]
I've googled the ETIMEOUT error, I've found people writing things like this:
![image](https://user-images.githubusercontent.com/42719082/84608274-80b0d500-aea9-11ea-8b0f-fdccba03f711.png)
Do you reckon that could be the issue, especially since all my other esx scripts are running perfectly so I don't think that would be a problem.

**Comment by RuisSoftware** [comment]
Hi, i will take a look now

**Comment by RuisSoftware** [comment]
Can you send me your version of async? 

Or send us a message on Discord, we can help you quicker there: https://dutch-players.nl/go/discord/

**Comment by ThatGuyJacobee** [comment]
Perfect, I'll DM you if that's alright. 😄

**Comment by RuisSoftware** [comment]
This issue is related to thenew mysql update. Just use this version: https://github.com/dutchplayers/fivem-mysql-async
