### ISSUE TITLE
[Shop Bug] After Pressing Menu Quickly

### ISSUE THREAD

**Issue by alexkoisine** [dutchplayers/FiveM-Resources#106]
Hi
I Found bug after pressing quickly up to 5 times on shops
I'm try to re download on github and try to server but still bug
Thanks
![image](https://user-images.githubusercontent.com/64629964/84558573-1ccdc580-ad5e-11ea-9c9e-c313c936f2e0.png)

https://streamable.com/epibrn

**Comment by macxitotruck** [comment]
hi, how did u do the shortcut key for item use ? i mean at ur weapon slot .  can i have your discord please?  tq

**Comment by RuisSoftware** [comment]
Your database is not quick enough to send the data to the client. When spamming it, it will break indeed.
