### ISSUE TITLE
no __resoursce.lua

### ISSUE THREAD

**Issue by round1234** [dutchplayers/FiveM-Resources#107]
Couldn't load resource esx-inventoryhud: Couldn't load resource esx-inventoryhud from resources:/esx-inventoryhud/: Could not open resource metadata file resources:/esx-inventoryhud//__resource.lua.

**Comment by RockySouthpaw** [comment]
Pretty sure you have a duplicate resource or the resource isn’t extracted properly.

**Comment by RuisSoftware** [comment]
You did not extract it correctly sir.
