### ISSUE TITLE
Weapons only drop with 1 bullet

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#108]
When I drop a weapon on the ground, the weapon drops with only one bullet.

**Comment by giorgos94** [comment]
Same thing that Im facing right now.
When I buy the weapon, I get it with the ammunition that Ive set on config.lua Ammo.
However, when I quit, it saves on the database with 0 ammo.

**Comment by wulfieh** [comment]
im guessing its because thats the number you have input on the inv, would be cool if it could get around it to drop weapon and ammo no matter the number

**Comment by RuisSoftware** [comment]
What if you change the number in the middle?

**Comment by RuisSoftware** [comment]
Check latest updates for personally saved ammo
