### ISSUE TITLE
Creating Shops

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#109]
**Describe the bug**
When I enter a new store into the config, save it, and restart the server nothing shows up at the coords I entered for the new shop

**To Reproduce**
1. Enter Shop into config
2. Save edit
3. restart server
4. Nothing appears

**Expected behavior**
My custom shop to appear at the place of the entered coords 

**ESX version:**
Extendedmode 

**Followed Wiki**
No info on the subject

**Comment by RuisSoftware** [comment]
EXM is not supported. We only support ESX1-final.
