### ISSUE TITLE
Duplicating items with an invited player in property

### ISSUE THREAD

**Issue by giorgos94** [dutchplayers/FiveM-Resources#111]
Hello there. I'm trying to set up an RP server using ESX 1.2 and your inventoryhud. Everything is pretty much workings as it's supposed to except for one this that I cannot find any solution for. I did remove esx_inventoryhud and did the exact same steps described below and the problem was not occuring. It does occur only with esx_inventoryhud and not with default es_extended hud.  

When I invite someone in my property, if he chooses to open the inventory of my property he can see my items. When he tries to move a said item from property storage to his player’s inventory, he is able to do it just fine. Problem is that the item does not get removed at all from my storage, therefore it’s duplicating.  

There is no posted solution anywhere about this issue. My Lua knowledge is limited because I recently started getting into scripting. I do not know what step could help me solve this one at all...

**Comment by ianvalls90** [comment]
Maybe there's some way to add a check like "If (guestinside) then (hidepropertystorage) else (showit)"...I'm just kinda guessing here tho

**Comment by RuisSoftware** [comment]
> 
> 
> Maybe there's some way to add a check like "If (guestinside) then (hidepropertystorage) else (showit)"...I'm just kinda guessing here tho

Nice try tho

**Comment by giorgos94** [comment]
I did edit and pushed a change for you that solves the issue.
Let me know if it works for you too

**Comment by RuisSoftware** [comment]
> 
> 
> I did edit and pushed a change for you that solves the issue.
> Let me know if it works for you too

I don't see any pull-request

**Comment by dutchplayers** [comment]
> 
> 
> > I did edit and pushed a change for you that solves the issue.
> > Let me know if it works for you too
> 
> I don't see any pull-request
