### ISSUE TITLE
BUG ITEMS WITH VAULT

### ISSUE THREAD

**Issue by sergiohacks3** [dutchplayers/FiveM-Resources#115]
is not compatible with vault ?? :(

![image](https://user-images.githubusercontent.com/20960370/85795903-54af1280-b739-11ea-8097-ce443fb771bf.png)

![image](https://user-images.githubusercontent.com/20960370/85795922-5c6eb700-b739-11ea-978c-a783885e228e.png)

**Comment by RuisSoftware** [comment]
Fixed with https://github.com/dutchplayers/monster_vault
