### ISSUE TITLE
small typo, shop.lua 288 .. PrisonShop

### ISSUE THREAD

**Issue by DocBurN** [dutchplayers/FiveM-Resources#116]
Super small typo.. could be already known

line 288, client/shop.lua

    instead of          for k, v in pairs(Config.Shops.YouTool.Locations) do
    it should be        for k, v in pairs(Config.Shops.PrisonShop.Locations) do

Double YouTool.. 
Thx for your work guys!

**Comment by RuisSoftware** [comment]
Thanks
