### ISSUE TITLE
I get this error when joining my server

### ISSUE THREAD

**Issue by xXMrPotatoXx** [dutchplayers/FiveM-Resources#118]
**Describe the bug**
I get this eror when joining my server
**To Reproduce**

**Expected behavior**

**Screenshots**
https://imgur.com/5u2mtyy

**ESX version:**
 - Version [I dont know]

**Additional context**

**Followed Wiki**
Yes/No No

**Comment by RuisSoftware** [comment]
Follow wiki https://github.com/dutchplayers/ESX-1.2-Inventory-HUD/wiki

**Comment by xXMrPotatoXx** [comment]
I dont see how to solve the issou on wiki

**Comment by RuisSoftware** [comment]
You have to extract the files from the ZIP. Extract esx_inventoryhud,  esx_inventoryhud_trunk and  esx_inventoryhud_glovebox

**Comment by RuisSoftware** [comment]
So; do **not** copy-paste the master folder.
