### ISSUE TITLE
lsrp-motels Bug inventory

### ISSUE THREAD

**Issue by FBFezz** [dutchplayers/FiveM-Resources#120]
**Describe the bug**
Missing export (View picture provided)

**To Reproduce**
1. Go to the motel
2. Open the inventory
3. See error

**Expected behavior**
Opens an inventory for the bed

**Screenshots**

![image](https://user-images.githubusercontent.com/43589668/86245896-16cf4580-bba2-11ea-9cfd-b3c9e11bc203.png)

**ESX version:**
 extendedmode v 1.0.1

**Additional context**
N/A

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Fixed in latest update :)
