### ISSUE TITLE
Bug with ESX.Menu items

### ISSUE THREAD

**Issue by imagreez** [dutchplayers/FiveM-Resources#121]
**Describe the bug**
When you use a item, it open a menu (ESX.Menu) the menu dosen't show up

**To Reproduce**
Use a item who open a ESX.Menu

**Expected behavior**
I say it in the describe the bug, the menu dosen't show up, but it works with the default inventory menu from esx

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Try adding the item in config.lua https://github.com/dutchplayers/ESX-1.2-Inventory-HUD/blob/master/esx_inventoryhud/config.lua#L11

**Comment by imagreez** [comment]
I added it and not work

**Comment by RuisSoftware** [comment]
Send the item registering code please

**Comment by imagreez** [comment]
Okey

```Lua
ESX.RegisterUsableItem('dni', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    local menu = "DNI"
    xPlayer.triggerEvent("roco_id:AbrirMenu", menu)
end)
```

**Comment by RuisSoftware** [comment]
Are you sure it was working with default menu?

Can you do:

```
Citizen.CreateThread(function()
  if IsControlJustReleased(0, 38) then
    local xPlayer = ESX.GetPlayerFromId(playerId)
    local menu = "DNI"
    xPlayer.triggerEvent("roco_id:AbrirMenu", menu)
  end
end)
```
OR
```
Citizen.CreateThread(function()
  if IsControlJustReleased(0, 38) then
    local xPlayer = ESX.GetPlayerFromId(source)
    local menu = "DNI"
    xPlayer.triggerEvent("roco_id:AbrirMenu", menu)
  end
end)
```

And see if the menu opens with E (or try another key)

**Comment by imagreez** [comment]
Yeah it works with default menu

**Comment by imagreez** [comment]
> Are you sure it was working with default menu?
> 
> Can you do:
> 
> ```
> Citizen.CreateThread(function()
>   if IsControlJustReleased(0, 38) then
>     local xPlayer = ESX.GetPlayerFromId(playerId)
>     local menu = "DNI"
>     xPlayer.triggerEvent("roco_id:AbrirMenu", menu)
>   end
> end)
> ```
> 
> OR
> 
> ```
> Citizen.CreateThread(function()
>   if IsControlJustReleased(0, 38) then
>     local xPlayer = ESX.GetPlayerFromId(source)
>     local menu = "DNI"
>     xPlayer.triggerEvent("roco_id:AbrirMenu", menu)
>   end
> end)
> ```
> 
> And see if the menu opens with E (or try another key)

It works. but with the intentoryhud dont work

**Comment by RuisSoftware** [comment]
I think you can't open a new menu from no menu

**Comment by RuisSoftware** [comment]
Create a menu first
