### ISSUE TITLE
Trunks Eventually Not Responding to Opening Key

### ISSUE THREAD

**Issue by TristGit** [dutchplayers/FiveM-Resources#122]
**Describe the bug**
![image](https://user-images.githubusercontent.com/57966174/86240675-77d12c00-bb56-11ea-97e8-6c0ac6687653.png)

This occurs when opening a vehicle that nobody owns, a world vehicle. Sometimes the menu is unable to be opened if a player accidentally presses the trunk key too many times. It seems clientside. I dont know if the error has something to do with it not working opening it,.

Also a possibly unrelated side note; even with the ownership set to true, you can still open most vehicles a side note: but you dont seem to be able to open trucks for some odd reason. I've since disabled it to false but havent tried yet.

But this error basically seems like its attempting to create another SQL data entry when it is opened.
Is this normal/inconsequential? Is there a way to disable the console?

**To Reproduce**
- Remapping the key to Y.
- Testing the open trunk inventory on world spawned vehicle.

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by iiAlphaWolf** [comment]
same issue

**Comment by sirakill** [comment]
same issue

**Comment by RuisSoftware** [comment]
Recently fixed
