### ISSUE TITLE
Couldn't load resource esx_invetoryhud/ could not open resource metadata file resources:/esx_inventoryhud//_resource.lua

### ISSUE THREAD

**Issue by JustRAMB0** [dutchplayers/FiveM-Resources#125]
when i try to enter in my fivem server i get this error. 
https://media.discordapp.net/attachments/722495748322623560/728985288445001728/unknown.png?width=1262&height=324
this is what the folder looks like
https://cdn.discordapp.com/attachments/722495748322623560/728990828017745920/unknown.png
i hope someone can help me fix this problem so that i can try out my fivem server.

**Comment by RockySouthpaw** [comment]
Do a search for esx_inventoryhud and remove the duplicate folder.

**Comment by JustRAMB0** [comment]
Fixed by renaming fxmanifest.lua to __resource (not 1 underscore but 2 for somereason)
