### ISSUE TITLE
Inventory Hotkeys

### ISSUE THREAD

**Issue by SkinnyDragonCodes** [dutchplayers/FiveM-Resources#126]
I am wondering if there is any chance of enhancement for adding hotkeys in the top row of the inventory to then have weapons and other consumable items. This could then get rid of the weapon wheel? 

there is a post on the cfxre forum showing screenshots of what I mean: 
https://forum.cfx.re/t/testing-new-hud-for-inventory-feedback/1084752

**Comment by bashon1** [comment]
have some issue 
did u find any way to fix it?

**Comment by RuisSoftware** [comment]
Added in v3!
