### ISSUE TITLE
Help with error not seeing the items on the inventory

### ISSUE THREAD

**Issue by raidzion** [dutchplayers/FiveM-Resources#128]
Hi i want to resolve this issue if its posible.
I opened the inventory and got the error on console, but i dont know whats happening i got the es_extended invenoty and works fine. Waiting for ur answers :D.
https://imgur.com/a/x0TtTKf

**Comment by RuisSoftware** [comment]
You are not using ESX 1.2, are you?

**Comment by raidzion** [comment]
I made a clean instalation on a new server and cant see it, i joined the discord if someone can help.
I downloaded the requirements of the wiki and followed all the steps. Waiting for ur answers

**Comment by RockySouthpaw** [comment]
Are you on 1.2 es_extended?

**Comment by raidzion** [comment]
Yes, i downloaded the exactly folder in the links that provides the wiki, i can show you.

**Comment by RuisSoftware** [comment]
getWeight = ESX1.2, send screenshot form es_extended fxmanifest bitte
