### ISSUE TITLE
Can't give or throw away items

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#129]
I recently installed this resource on a server and it works perfectly. But when I try to give an item to another player or throw it away, it doesn't work. It only works with money and guns. Everything should be on the latest version and I tried several things to fix this but it just don't work.

Would be really cool if someone could help me :)

**Comment by RuisSoftware** [comment]
ESX 1.2?

**Comment by ghost** [comment]
> ESX 1.2?

I think so. Maybe you could send me a link for this and i check if it's matching with my version.

**Comment by RuisSoftware** [comment]
Just open the fxmanifest from es_extended

**Comment by ghost** [comment]
Ok, you were right. I made a mistake with esx version. Thanks for fast reply :)
