### ISSUE TITLE
Shops not working

### ISSUE THREAD

**Issue by Gregorsaur** [dutchplayers/FiveM-Resources#13]
Shops don't work. 

I changed manifest to point to right location. But now the shops open and it says secondary inventory not available.

**Comment by heyheyitsmeman** [comment]
Same issue.

**Comment by xDope7137** [comment]
'@mysql-async/lib/MySQL.lua'

add this to __resource.lua in server side.

**Comment by ClicheUsername** [comment]
This should be fixed with #20 -- make sure you download the latest version.
