### ISSUE TITLE
Cant seem to drop and give money but everything else works

### ISSUE THREAD

**Issue by DavidFdes** [dutchplayers/FiveM-Resources#130]
As the title says, cant seem to drop and give money but everything else works.
Theres no console error, no client error, nothing. Cant drop or give money.

**Comment by RuisSoftware** [comment]
Related to https://github.com/dutchplayers/ESX-1.2-Inventory-HUD/issues/129

**Comment by DavidFdes** [comment]
Sorry what do i need to do in fxmanifest ?

**Comment by RockySouthpaw** [comment]
They’re stating your issue is a result of being on an incompatible es_extended. Update your es_extended to 1.2 (v1 final)

**Comment by DavidFdes** [comment]
Brain fart, i thought i needed to add something, thanks! 
One more thing how do i make a new account not droppable or robbable ?
