### ISSUE TITLE
Policejob money visual glitch?

### ISSUE THREAD

**Issue by iiAlphaWolf** [dutchplayers/FiveM-Resources#134]
**Describe the bug**
When a policemen opens someones inventory the policemen will see there money but three times. its not duped or anything its just visual glitched i guess. Any way to fix this?

**Screenshots**
![image](https://user-images.githubusercontent.com/30497126/88198100-a3ba6b80-cc43-11ea-9e84-50f14244e834.png)

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Did you change the config?

**Comment by iiAlphaWolf** [comment]
> Did you change the config?

No i did what it said on the wiki. Removed the default stuff and put your lines there, nothing else.
And i forgot to say, we are only able to remove money, no items from the searched player.

**Comment by iiAlphaWolf** [comment]
Fixed in latest update!
