### ISSUE TITLE
Trunk small detail

### ISSUE THREAD

**Issue by DocBurN** [dutchplayers/FiveM-Resources#135]
![image](https://user-images.githubusercontent.com/49012555/88213771-326cbf80-cc27-11ea-93bc-3dc1bffae3b8.png)

its not really an issues or a huge one but its the only thing outside the config that i need to change from the code every time i update.. line 188 from trunk client

Lets say im driving a cheapass emperor.. which is a long car.. i thing the range of the 2.0 dont reach the center of the car.. the trunk animation wont trigger open.. changing it to "bigger".. i used 4.0.. now the trunk open, visually..

local vehicle = GetClosestVehicle(pos["x"], pos["y"], pos["z"], 2.0, 0, 70)
to
local vehicle = GetClosestVehicle(pos["x"], pos["y"], pos["z"], 4.0, 0, 70)

other than that.. thank you for your work! keeping this vital script alive and improoved. Merci beaucoup!

**Comment by RuisSoftware** [comment]
Thank you very much for this little improvement!
