### ISSUE TITLE
Problem with using TokoVoip

### ISSUE THREAD

**Issue by ItayKisous** [dutchplayers/FiveM-Resources#140]
when opening the phone (via draging the radio to the use button), the radio opens up, but after you close your radio, the inventory is still open and you have to restart the script in order to close it.

**Comment by RockySouthpaw** [comment]
Why not just make a client event within esx_inventoryhud that closes the inventory and then trigger said event after you close the radio?

If it’s a useable item all you have to do is literally go into the config and set it so it closes it. This issue isn’t even something caused by the inventory.

**Comment by JayaX-iCore** [comment]
Go Your config and in Config.CloseUiItems Type radio
