### ISSUE TITLE
Weapon withdraw property

### ISSUE THREAD

**Issue by imagreez** [dutchplayers/FiveM-Resources#141]
**Describe the bug**
When you try to withdraw a weapon, is not possible and give the error:
```lua
SCRIPT ERROR: @esx_property/server/main.lua:255: attempt to index a nil value (global 'data')
> handler (@esx_datastore/server/main.lua:69)
> handler (@esx_property/server/main.lua:253)
```
**To Reproduce**
1. Insert waepon to property
2. Withdraw it
3. See error

**Expected behavior**
The weapon go to inventory of the player

**Screenshots**

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Recently fixed
