### ISSUE TITLE
Property inventory inserts or withdraws in the player property and not to the other player

### ISSUE THREAD

**Issue by imagreez** [dutchplayers/FiveM-Resources#142]
**Describe the bug**
When you try to insert or withdraw in other property where you are invited, the inventory tries in the player who excute action property and not in the other player property.

**To Reproduce**
1. A friend invites to his property
2. You open his property inventory
3. You try to insert
4. You go to your property
5. You have the item you inserted in the friend house in your property

**Expected behavior**
The item inserts in the friend house

**Screenshots**

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Fixed
