### ISSUE TITLE
Couldn't load resource ESX-1.2-Inventory: Couldn't load resource ESX-1.2-Inventory from resources:/ESX-1.2-Inventory/: Could not open resource metadata file resources:/ESX-1.2-Inventory//__resource.lua.

### ISSUE THREAD

**Issue by TheAxe99** [dutchplayers/FiveM-Resources#143]
Couldn't load resource ESX-1.2-Inventory: Couldn't load resource ESX-1.2-Inventory from resources:/ESX-1.2-Inventory/: Could not open resource metadata file resources:/ESX-1.2-Inventory//__resource.lua.

**Comment by kyledeluxe** [comment]
Thats related to how you uploaded it.
You cant just take the hole folder and make it one.
You have to  start each of the resources as their own.
And it will work.
