### ISSUE TITLE
Weight does not seem to work :/

### ISSUE THREAD

**Issue by iiAlphaWolf** [dutchplayers/FiveM-Resources#144]
![image](https://user-images.githubusercontent.com/30497126/89061774-98fb8700-d365-11ea-8327-a058d885c4b6.png)
I guess this explains the problem already. weed keeps stacking up while inventory weight is full? How can i solve this in the database its all good i think there's a screenshot:
![image](https://user-images.githubusercontent.com/30497126/89061868-c6483500-d365-11ea-93ba-83f5b0d273d3.png)

I use the final v1 esx, and latest version of ur inventory

**Followed Wiki**
Jep

**Comment by iiAlphaWolf** [comment]
Its also when users do weed and stuff they get the item and it overwrites the inventory limit.. just like /giveitem command does. Anyway to solve this?

**Comment by RuisSoftware** [comment]
This is because your other resource is pushing the items. Not related to inventory
