### ISSUE TITLE
Weapon Ammo not Sync when Re-Join Server

### ISSUE THREAD

**Issue by awidyaandika** [dutchplayers/FiveM-Resources#145]
Hello guys, I want to ask something. Why my weapon ammo does not sync when I re-join the server? 

Example:
I have 2 pistols in my inventory, the ammo is 430, then I disconnect from the server and then I join again to the server. My pistol ammo reduces 430 to 24.
And this also happens in shotgun weapons,

Assumption:
I think the problem in a similar weapon (same type), I try to buy 1000 ammo and only have 1 weapon and the ammo sync works but I buy 1000 ammo and have 2 weapons with the same type, the ammo will reset to 24 ammo after I re-join to the server.

Any solution to this problem? I hope someone can help me to fix this problem, Thx...

**Comment by NazriGenfil** [comment]
just like me, there is a solution?

**Comment by Dokman** [comment]
this is just as normal as possible, the database stores a hash of a weapon and the owner, so if they have 2 this will create a bug. Just update the script and put only one of this in your inventory recharged with ammo
