### ISSUE TITLE
Take items from an inventory

### ISSUE THREAD

**Issue by HonorAlterium** [dutchplayers/FiveM-Resources#15]
Using /openinventory can see the player objects but cannot take them from the player inventory, you can only put item in the player inventory, same too the police search menu.

**Comment by terbaek** [comment]
shop inventory cannot use... how to fix this problem?

**Comment by RuisSoftware** [comment]
> 
> 
> shop inventory cannot use... how to fix this problem?

This is not related to this issue.

**Comment by christerjohansson** [comment]
I have same issue, can't take items from vehicle inventory to player inventory. It works for a while when installed fresh, but then stops working.

**Comment by RuisSoftware** [comment]
Fixed in latest updates
