### ISSUE TITLE
Is this working with esx final version?

### ISSUE THREAD

**Issue by goodguydul** [dutchplayers/FiveM-Resources#151]
Is this working with esx final version?
all shops items not showing

**Comment by RockySouthpaw** [comment]
States on the read me it’s supported for es_extended 1.2 which is the same version as final v1 if you look at the fxmanifest.

**Comment by goodguydul** [comment]
but, after i updated esx to final version, the shop items disappeared.

**Comment by RuisSoftware** [comment]
Use the latest updates 👍
