### ISSUE TITLE
No inventory within the `weaponshopPolice` shop

### ISSUE THREAD

**Issue by gamerbiggie** [dutchplayers/FiveM-Resources#152]
![image](https://user-images.githubusercontent.com/56044637/89719350-4d795680-d9bf-11ea-9696-57d80c3a8000.png)
![image](https://user-images.githubusercontent.com/56044637/89719360-5bc77280-d9bf-11ea-89c8-4eea601a09f4.png)

Looking at the images you can see what is meant to be within the inventory of the PoliceShop, however it is empty.

Tried looking through too see how it is creating the inventory but couldn't see any issues. I couldn't find anything listed in previous issues so though I would make this.

Any ideas?

**Comment by LeoLight868** [comment]
are the items added to your database?

**Comment by gamerbiggie** [comment]
I got this fixed. Turns out the inventory isn't actually set up fully and needed to be added to the list to actually pull the items from the config and put them in the store
