### ISSUE TITLE
Clearing car inventory after using impound

### ISSUE THREAD

**Issue by Arsalan0098** [dutchplayers/FiveM-Resources#153]
Hello guys, i am using esx_advancedGarage and i wanted to clear trunk inventory after the person use Impound so all the items in car should be gone. i add code this in my advancedgarage
client side when he spawncehicle from impound :
`TriggerServerEvent('esx_advancedgarage:cleartrunk',data.current.value.plate)`
and server side:
`RegisterServerEvent('esx_advancedgarage:cleartrunk')
AddEventHandler('esx_advancedgarage:cleartrunk', function(plate)
    MySQL.Async.execute(
        "UPDATE trunk_inventory SET data = @data WHERE plate = @plate",
        {
          ["@plate"] = plate,
          ["@data"] = '{"coffre":[]}'
        }
    )
end)`
![Capture](https://user-images.githubusercontent.com/2874141/89727532-15175e00-da3b-11ea-8edf-2c1e148600fd.PNG)

it is working and this code clear the information in Trunk_inventory database, but when i open inventory they are still there.
any idea how it works?
database before using impound:
![Capture1](https://user-images.githubusercontent.com/2874141/89727540-1fd1f300-da3b-11ea-9fe1-916bb62bafc3.PNG)
Database after using impound:
![Capture3](https://user-images.githubusercontent.com/2874141/89727543-28c2c480-da3b-11ea-9f39-0b0019717751.PNG)
car inventory after using impound:
![Capture4](https://user-images.githubusercontent.com/2874141/89727547-311aff80-da3b-11ea-8fdd-4836e953f002.PNG)

**Comment by RuisSoftware** [comment]
Sorry for delay here, we are more active in our Discord server.

I use your resource too and this feature is nice. I am going to try something and will report back here

**Comment by RuisSoftware** [comment]
You should trigger function loadInvent(plate) somewere

**Comment by Arsalan0098** [comment]
i dont know how too trigger it in server side, can you give me some help? or add something like everytime someone try to open inventory first loadInvent(plate)?
thanks
