### ISSUE TITLE
SECUNDAIRE INVENTARIS IS NIET BESCHIKBAAR.

### ISSUE THREAD

**Issue by pixelroll** [dutchplayers/FiveM-Resources#154]
**Describe the bug**
when I open in a car or next door he says SECUNDARY INVENTARIS IS NIET BESCHIKBAAR. How to activate it?

**Screenshots**
https://i.imgur.com/AFISO3R.png

**ESX version:**
 https://github.com/extendedmode/extendedmode

**Comment by RuisSoftware** [comment]
Use the trunk or glovebox keybinding
