### ISSUE TITLE
trunk glitch

### ISSUE THREAD

**Issue by xrtw** [dutchplayers/FiveM-Resources#159]
when you disconnect your internet cable, you just drop guns into trunk from inventory, after that, connect it into modem and now you have your glitched guns

**Comment by Tinky124** [comment]
Yea can confirm this bug @dutchplayers

**Comment by Heavens-c** [comment]
just try to put a kg on trunk to solve the issue.. :)

**Comment by Heavens-c** [comment]
![image](https://user-images.githubusercontent.com/60640873/92184164-0b8ae580-ee83-11ea-86be-b1b09bc5d06b.png)
