### ISSUE TITLE
ShopWeaponPolice

### ISSUE THREAD

**Issue by goncalocarvalho95** [dutchplayers/FiveM-Resources#160]
When I click to open the Police Weapon Shop the weapons dont show on secondary inventory.
I'm using ESX v1.2 from esx-framework github.

**Comment by madhatter23412** [comment]
I had to add this to the server/main.lua for inventoryhud. 


if shoptype == "weaponshopPolice" then
			local weapons = Config.Shops.WeaponShopPolice.Weapons
			for _, v in pairs(Config.Shops.WeaponShopPolice.Weapons) do
				if v.name == itemResult[i].name then
					table.insert(itemShopList, {
						type = "item_weapon",
						name = itemInformation[itemResult[i].name].name,
						label = itemInformation[itemResult[i].name].label,
						weight = 1,
						ammo = v.ammo,
						rare = itemInformation[itemResult[i].name].rare,
						can_remove = itemInformation[itemResult[i].name].can_remove,
						price = itemInformation[itemResult[i].name].price,
						count = 99999999
					})
				end
			end

			local ammo = Config.Shops.WeaponShopPolice.Ammo
			for _,v in pairs(Config.Shops.WeaponShopPolice.Ammo) do
				if v.name == itemResult[i].name then
					table.insert(itemShopList, {
						type = "item_ammo",
						name = itemInformation[itemResult[i].name].name,
						label = itemInformation[itemResult[i].name].label,
						weight = 1,
						weaponhash = v.weaponhash,
						ammo = v.ammo,
						rare = itemInformation[itemResult[i].name].rare,
						can_remove = itemInformation[itemResult[i].name].can_remove,
						price = itemInformation[itemResult[i].name].price,
						count = 99999999
					})
				end
			end

			for _, v in pairs(Config.Shops.WeaponShopPolice.Items) do
				if v.name == itemResult[i].name then
					table.insert(itemShopList, {
						type = "item_standard",
						name = itemInformation[itemResult[i].name].name,
						label = itemInformation[itemResult[i].name].label,
						weight = itemInformation[itemResult[i].name].weight,
						rare = itemInformation[itemResult[i].name].rare,
						can_remove = itemInformation[itemResult[i].name].can_remove,
						price = itemInformation[itemResult[i].name].price,
						count = 99999999
					})
				end
			end
		end

**Comment by RuisSoftware** [comment]
Check latest master branch for fix
