### ISSUE TITLE
Item labels nil when storing/taking out items (esx_property/esx_inventoryhud)

### ISSUE THREAD

**Issue by Rhydium** [dutchplayers/FiveM-Resources#161]
**Describe the bug**
When taking out/storing an item in esx_property (with esx_inventoryhud) item labels are `nil` (You have stored 1x nil)

**To Reproduce**
1. Go to your property
2. Open the inventory
3. Store an item like bread or take an item like bread out

**Expected behavior**
Label in stead of `nil`

**Screenshots**
![image](https://user-images.githubusercontent.com/25478879/91082523-122a8900-e649-11ea-9722-5af3ae3e7616.png)

**ESX version:**
 - 1.2

**Additional context**
No additional context

**Comment by RuisSoftware** [comment]
Retry the latest master branch update and report back
