### ISSUE TITLE
Inventory not rescaling on all resolutions fix :)

### ISSUE THREAD

**Issue by Kieeefman** [dutchplayers/FiveM-Resources#164]
@media (max-width: 1500px) {
    .inventory {
        width: 1300px;
    }

    #playerInventory {
        width: 550px;
    }

    #controls {
        width: 200px;
    }

    #otherInventory {
        width: 550px;
    }

    #noSecondInventoryMessage {
        width: 540px;
    }
}

@media (max-width: 1300px) {
    .inventory {
        width: 1000px;
    }

    #playerInventory {
        width: 425px;
    }

    #controls {
        width: 150px;
    }

    #otherInventory {
        width: 425px;
    }

    #noSecondInventoryMessage {
        width: 420px;
    }
}

Add this to ui.css on the bottom of the file and you can adjust the value width on diferrent resolutions.

**Comment by RuisSoftware** [comment]
Amazing work. We will try this out.

If you do a PR< you also get your respective roles ;)

**Comment by RuisSoftware** [comment]
Merged
