### ISSUE TITLE
Trunk glitch, dupe weapons..

### ISSUE THREAD

**Issue by Tinky124** [dutchplayers/FiveM-Resources#166]
when you disconnect your internet cable, you just drop guns into trunk from inventory, after that, connect it into modem and now you have your glitched guns

Video if you dont understand:
https://youtu.be/IjHlF6VuPU0?t=23

Another video with lag switch:
https://youtu.be/kHOfmdVLs1A?t=81

I tried everything to fix this but i cant i dont know, if you can fix this,thanks!!!

**Comment by Heavens-c** [comment]
legit glitch i tried too ...

**Comment by SyntaxFail** [comment]
Well by so Tutorials one can bypass it now well. 1st solution: KickHighPing Script. Then players with a ping of more than 200ms will be kicked.
2nd solution: You build in the script when you put something in the trunk that closes the inventory. This is a bit more work for the players but more protection against that, because the glitcher have no chance to open the inventory again. I would do both solutions.

**Comment by RuisSoftware** [comment]
Can you try with the latest master branch?

**Comment by Tinky124** [comment]
It will get error easy fix for this is just put check if player hasitemweapon and it will work!
like this code:

```lua
if type == "item_weapon" then
      TriggerEvent("esx_trunk:getSharedDataStore",plate,function(store)
	  if xPlayer.hasWeapon(item) then -- this fix the problem!!! 👍 
		local storeWeapons = store.get("weapons")

          if storeWeapons == nil then
            storeWeapons = {}
          end

          table.insert(
            storeWeapons,
            {
              name = item,
              label = label,
              ammo = count
            }
          )
          if (getTotalInventoryWeight(plate) + (getItemWeight(item))) > max then
            TriggerClientEvent(
              "pNotify:SendNotification",
              _source,
              {
                text = _U("invalid_amount"),
                type = "error",
                queue = "trunk",
                timeout = 3000,
                layout = "bottomCenter"
              }
            )
          else
            store.set("weapons", storeWeapons)
            xPlayer.removeWeapon(item)

            MySQL.Async.execute("UPDATE trunk_inventory SET owned = @owned WHERE plate = @plate", {
                ["@plate"] = plate,
                ["@owned"] = owned
              }
            )
		end
          end
        end)
    end
```

**Comment by wUnp23** [comment]
Still works but only on servers that run qb-inventory. Most of them that run different inv system have it already covered and you might see the guns duped but the moment you exit the trunk or try to move them into your inv, they will disappear (tried on multiple servers, qb-inventory is the only one that works till now as of 19/05/2024 and I did get permabanned for it cuz somehow the admins can see errors while I dupe items so even though it works, you will be banned if caught so do this with caution).
