### ISSUE TITLE
esx properties with hud issue?

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#167]
https://gyazo.com/42506f90ccdde9d7810ffe82dc395e62 so i finally got everything to work after error and error anyways then this problem occurs, how can i disable the ui from the esx properties?

**Comment by SkinnyDragonCodes** [comment]
im pretty sure you do this in the property script and make sure the standard event is removed abit like when you implement this inventory you have to disable the standard esx f2 menu. // im pretty sure it tells you how to do this in the WIKI / FAQ

**Comment by SkinnyDragonCodes** [comment]
@Falyandar can you show me what you put to get it to load using inventoryhud?

**Comment by RuisSoftware** [comment]
Solution is in the wiki
