### ISSUE TITLE
New version 3 does not work?

### ISSUE THREAD

**Issue by SkinnyDragonCodes** [dutchplayers/FiveM-Resources#168]
the new version does not seem to work

when i open my inventory the inventory will be blank, after spamming f2 a few times it will show my items but it does not overlay my mouse to allow me to move about in the inventory.

esx 1.2 - correct version of ESX.. my inventory worked before this update..

Also i do not get any errors in the console on the f8 client side.

**Comment by SkinnyDragonCodes** [comment]
I have fixed that issue as you had to hold f2... i changed the client.lua line 36 from: 

if IsDisabledControlJustPressed(0, Config.OpenControl) and GetLastInputMethod(0) then

TO 

if IsControlJustReleased(0, Config.OpenControl) and IsInputDisabled(0) then

**Comment by RuisSoftware** [comment]
Thank you!
