### ISSUE TITLE
'@mysql-async/lib/MySQL.lua'

### ISSUE THREAD

**Issue by xDope7137** [dutchplayers/FiveM-Resources#17]
'@mysql-async/lib/MySQL.lua'

add this to __resource.lua in server side.

_Originally posted by @xDope7137 in https://github.com/dutchplayers/esx-inventoryhud/issues/13#issuecomment-615417322_

**Comment by XXMarkicX** [comment]
Hey, while your "fix" indeed fixed error in my server CMD it still doesn't display the items. Would you mind giving me discord assistance please?

Thanks in advance!

**Comment by XXMarkicX** [comment]
> 
> 
> '@mysql-async/lib/MySQL.lua'
> 
> add this to __resource.lua in server side.
> 
> _Originally posted by @xDope7137 in [#13 (comment)](https://github.com/dutchplayers/esx-inventoryhud/issues/13#issuecomment-615417322)_

Hey, while your "fix" indeed fixed error in my server CMD it still doesn't display the items. Would you mind giving me discord assistance please?

Thanks in advance!

**Comment by xDope7137** [comment]
> > '@mysql-async/lib/MySQL.lua'
> > add this to __resource.lua in server side.
> > _Originally posted by @xDope7137 in [#13 (comment)](https://github.com/dutchplayers/esx-inventoryhud/issues/13#issuecomment-615417322)_
> 
> Hey, while your "fix" indeed fixed error in my server CMD it still doesn't display the items. Would you mind giving me discord assistance please?
> 
> Thanks in advance!

Make sure you have items mentioned in config.lua in the items table in SQL. xdope#2788

**Comment by theprelior** [comment]
> > > '@mysql-async/lib/MySQL.lua'
> > > add this to __resource.lua in server side.
> > > _Originally posted by @xDope7137 in [#13 (comment)](https://github.com/dutchplayers/esx-inventoryhud/issues/13#issuecomment-615417322)_
> > 
> > 
> > Hey, while your "fix" indeed fixed error in my server CMD it still doesn't display the items. Would you mind giving me discord assistance please?
> > Thanks in advance!
> 
> Make sure you have items mentioned in config.lua in the items table in SQL. xdope#2788

I already have done but it's still same
It can't fetch data from the db.

**Comment by XXMarkicX** [comment]
> 
> 
> > > '@mysql-async/lib/MySQL.lua'
> > > add this to __resource.lua in server side.
> > > _Originally posted by @xDope7137 in [#13 (comment)](https://github.com/dutchplayers/esx-inventoryhud/issues/13#issuecomment-615417322)_
> > 
> > 
> > Hey, while your "fix" indeed fixed error in my server CMD it still doesn't display the items. Would you mind giving me discord assistance please?
> > Thanks in advance!
> 
> Make sure you have items mentioned in config.lua in the items table in SQL. xdope#2788

Hey, I think I did everything according to your instructions. I added you on discord, my name is Mark there would you be willing to take a look at my changes and see if I did them correct ?

**Comment by ClicheUsername** [comment]
This should be fixed with #20 -- make sure you download the latest version.
