### ISSUE TITLE
Resolution Problem

### ISSUE THREAD

**Issue by fucekar** [dutchplayers/FiveM-Resources#170]
**Describe the bug**
So Inventory Still Have Big Problem And Cannot Usable
![image](https://user-images.githubusercontent.com/69375242/93008624-0537f000-f58c-11ea-9f2c-aac837ab9823.png)
not fix for 1440X900 and lower
this great and good for upper but for 1440X900 and lower not

**Comment by fucekar** [comment]
ok now this is so big problem and people with under 1440x900 cannot use inventory
fix?

**Comment by RuisSoftware** [comment]
For now you can use v2.4

We will improve this in future

**Comment by fucekar** [comment]
im using v2.4 about 3.4 month ;D
im waiting for v3

**Comment by RuisSoftware** [comment]
:S we're busy sorry

**Comment by ShyKaZa** [comment]
True i know that fucekar i think and hope if some of us contributors will find fix or have time to add code from 2.4 version to v3 with litte changes we are good. :D

**Comment by ElecTwix** [comment]
Same problem

**Comment by fucekar** [comment]
hi this not fixes?

**Comment by fucekar** [comment]
this is still not fixed or is fixed?

**Comment by ShyKaZa** [comment]
Fixed already 10 times also i dont do fivem anymore its trash

Dňa st 24. 2. 2021, 1:33 fucekar <notifications@github.com> napísal(a):
