### ISSUE TITLE
not a issuse just help ...

### ISSUE THREAD

**Issue by fucekar** [dutchplayers/FiveM-Resources#171]
fa.js :

var invLocale = new Object();
invLocale.dropItem = "Andakhtan";
invLocale.useItem = "Estefade";
invLocale.giveItem = "Dadan";
invLocale.secondInventoryNotAvailable = "Inventory Dovom Dar Dastres Nist.";
fa.lua :

Locales["fa"] = {
	["cash"] = "Pol Naghd",
	["black_money"] = "Pol Kasif",
	["player_nearby"] = "Fardi Dige Dar In Nazdiki Nist!",
	["players_nearby"] = "Fardi Dar In Nazdiki Nist!",
	["openinv_help"] = "Baz Kardan Inventory Baghiye.",
	["openinv_id"] = "Shenase Fard",
	["no_permissions"] = "Shoma Dastresi Kafi Baraye In Ra Nadarid!",
	["no_player"] = "In Fard Vojod Nadarad!",
	["player_inventory"] = "Inventory Fard",
	["stealing"] = "Shoma Darhal Dozdi Az Kasi Hastid",
	["yes"] = "Bale",
	["no"] = "Kheir",
	["player_inventory_weight"] = "Vazn Inventory",
	["nacho_veh"] = "In Vehicle Shoma Nist.",
	["player_inv_no_space"] = "Shoma Fazaye Khali Nadarid.",
	["insufficient_space"] = "Shoma Fazaye Khali Nadarid.",
	["weapon_exist"] = "Shoma Darhal Hazer In Weapon Ra Darid.",
	["weapon_exist_give"] = "Fard In Weapon Ra Darad.",
	["reloaded"] = "Reloaded",
	["max_ammo"] = "Hadeaksar Tir",
	["no_weapon"] = "You do not own the weapon for this ammo type!",
	["invalid_quantity"] = "Meghdar Namotabar Ast.",
	["item_added"] = "Ezafe Shod:",
	["item_removed"] = "Hazf Shod:",
	["money_added"] = "Ezafe Shod:",
	["money_removed"] = "Hazf Shod:",
	["weapon_added"] = "Ezafe Shod:",
	["weapon_removed"] = "Hazf Shod:",
	["no_money"] = "Shoma Pol Kafi Nadarid.",
	['shop_press_menu'] = 'Bezanid Roye ~INPUT_CONTEXT~ Baraye Dastresi Be ~y~store~s~.',
    ['regular_shop_name'] = 'SuperMarket',
	['blackmarket_shop_name'] = 'Bazar Siah',
    ['robs_liquor_name'] = 'Liquor store',
    ['you_tool_name'] = 'Hardware store',
   	['prison_shop_name'] = 'Prison Commissioner',
	['weapon_shop_name'] = 'AmmuNation',
	['drug_shop_name'] = 'Drug Shop',
	['nightclub_shop_name'] = 'Nightclub',
	['police_shop_name'] = 'Police Shop',
	['license_shop_title'] = 'Sabt Mojavez?',
	['license_shop_help'] = 'press ~INPUT_CONTEXT~ to register license',
	['license_shop_check'] = 'Shoma Darhal Hazer Mojavez Aslahe Darid!',
	['license_check_fail'] = 'Shoma Baraye Kharid Weapon Niaz Be Movajez Darid!',
	['blackmarket_shop_name'] = 'Bazar Siah',	
	["bed_stash"] = "Bed Stash",
	["motels"] = "Motel Inventory",
	["trunk"] = "Trunk Inventory",
	["glovebox"] = "Glovebox Inventory",
	["store"] = "Supermarket",
	["vault"] = "Vault",
	["weapon_pulled"] = "Selah Keshide Shod",	
	["error"] = "Khataei Rokh Dade Ast.",
	["not_compatible"] = "This attachment is not compatible or is already equipped.",
	["no_weapon_selected"] = "Aslahe Entekhab Nashode Ast.",
	["no_attachment"] = "This weapon does not have this attachment.",
	["no_gun_in_hand"] = "Shoma Dar Dast Khod Aslahe Nadarid.",	
	["open_shop"] = "Bezanid Roye [~g~E~w~] Baraye Baz Kardan Shop",
	["no_acces"] = "Dastresi Be In Foroshgah Vojod Nadarad.",
}

this is for Iranians , Persian 
thanks for create this awesome inventory

**Comment by RuisSoftware** [comment]
Thanks a lot! It's merged :)
