### ISSUE TITLE
shops not work...

### ISSUE THREAD

**Issue by fucekar** [dutchplayers/FiveM-Resources#174]
SCRIPT ERROR: @esx_inventoryhud/server/main.lua:342: attempt to perform arithmetic on a nil value (field 'price')
SCRIPT ERROR: @esx_inventoryhud/server/main.lua:342: attempt to perform arithmetic on a nil value (field 'price')
when you want to buy a item from shop this happen
i have price in my databse
v2 work
v3 problem

**Comment by RuisSoftware** [comment]
Price is in config, do not just copy paste your old config

**Comment by RuisSoftware** [comment]
Last comit fixed the default

**Comment by fucekar** [comment]
ehh
        Items = {
            {name = 'bread' price = 1},
            {name = 'water' price = 1},
            {name = 'lemon' price = 1},
            {name = 'phone' price = 1},
            {name = 'hamburger' price = 1},
            {name = 'icedcoffee' price = 1},
            {name = 'juice' price = 1},
            {name = 'coffeecup' price = 1},
            {name = 'cucumbers' price = 1},
            {name = 'garlic' price = 1},
            {name = 'energy' price = 1},
            {name = 'lemonade' price = 1},
            {name = 'banana' price = 1},
            {name = 'dildo' price = 1},
            {name = 'icetea' price = 1},
            {name = 'sim' price = 1}     
        }
    },
thats mine now i replace this but
Error parsing script @esx_inventoryhud/config.lua in resource esx_inventoryhud: @esx_inventoryhud/config.lua:65: '}' expected near 'price'
Failed to load script config.lua.

**Comment by RuisSoftware** [comment]
lol i see :')

**Comment by fucekar** [comment]
an small ques
what do price in database do now!?

**Comment by fucekar** [comment]
:D

**Comment by RuisSoftware** [comment]
It's fixed now
