### ISSUE TITLE
So Big problem with trunk/glovebox (just weapon)

### ISSUE THREAD

**Issue by fucekar** [dutchplayers/FiveM-Resources#175]
ok if you move your weapon from your inventory to trunk or glovebox your weapon deleted :|
its deleted in your inventory and not moved in trunk or glovebox

**Comment by fucekar** [comment]
no any error anywhere

**Comment by BladesJT** [comment]
Did you find a fix? Currently having this problem also. Things like bread and water store fine but guns do not

**Comment by fucekar** [comment]
hi still not i have the issue , i wait to new update

**Comment by davepiersma** [comment]
Make sure you add the weapons as ITEMS in your DB.  
Also make sure you have disc weapon and disc ammo installed.


```
INSERT INTO `items` (`name`, `label`, `weight`) VALUES 
('WEAPON_FLASHLIGHT', 'Flashlight', 1),
('WEAPON_STUNGUN', 'Taser', 100),
('WEAPON_KNIFE', 'Knife', 100),
('WEAPON_BAT', 'Baseball Bat', 1),
('WEAPON_ADVANCEDRIFLE', 'Advanced Rifle', 1),
('WEAPON_APPISTOL', 'AP Pistol', 1),
('WEAPON_ASSAULTRIFLE', 'Assault Rifle', 1),
('WEAPON_ASSAULTSHOTGUN', 'Assault Shotgun', 1),
('WEAPON_ASSAULTSMG', 'Assault SMG', 1),
('WEAPON_AUTOSHOTGUN', 'Auto Shotgun', 1),
('WEAPON_CARBINERIFLE', 'Carbine Rifle', 1),
('WEAPON_COMBATPISTOL', 'Combat Pistol', 1),
('WEAPON_PISTOL', 'Pistol', 1),
('WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 1),
('WEAPON_SMG', 'SMG', 1),
('flashlight', 'Flashlight', 2),
('grip', 'Grip', 2),
('scope', 'Scope', 2),
('skin', 'Skin', 2),
('supressor', 'Suppressor', 2);
```

**Comment by BladesJT** [comment]
I've got those entries in my `ITEMS` table in my database. I've not got the disc-weapons resource though. Do you know where I can get this from? Done a search but cannot find it anywhere.

**Comment by minirovi95** [comment]
tengo el mismo problema... porfavor alguien me puede ayudar?

**Comment by RuisSoftware** [comment]
Recently fixede
