### ISSUE TITLE
Property.lua error

### ISSUE THREAD

**Issue by davepiersma** [dutchplayers/FiveM-Resources#176]
**Describe the bug**
@esx_inventoryhud/client/property.lua:32: attempt to compare number with nil

**To Reproduce**
1. Go to Appartment.
2. Try to open safe.
3. error returns @esx_inventoryhud/client/property.lua:32: attempt to compare number with nil

**Expected behavior**
Open the safe :') 

**ESX version:**
 - Version 1.0 final

**Additional context**
problem occurs at 

```
if money > 0 then
        accountData = {
            label = _U("money"),
            count = money,
            type = "item_account",
            name = "money",
            usable = false,
            rare = false,
            weight = 0,
            canRemove = false
        }
        table.insert(items, accountData)
    end
```

**Followed Wiki**
Yes

**Comment by davepiersma** [comment]
@dutchplayers Je hulp word gewaardeerd 👍

**Comment by RuisSoftware** [comment]
Hey, v3 geeft helaas wat meer bugs dan verwacht, hiervoor wordt even geen ondersteuning geboden tot de nieuwe update. We raden je aan om versie 2.4 te downloaden, te laatste voor de hotbar update. Hiervoor kan je alle ondersteuning krijgen nu, het snelst via onze Discord server ;)

**Comment by davepiersma** [comment]
Ah vandaar, je bent een topper. Ik ga kijken of de vorige versie het beter doet ! Thanks!
