### ISSUE TITLE
ER_DUP_ENTRY: Duplicate entry ' YUY405 ' for key 'plate'

### ISSUE THREAD

**Issue by DavidFdes** [dutchplayers/FiveM-Resources#178]
Sometimes while trying to open glovebox or trunk, this happens.

[MariaDB:10.4.14-MariaDB] [ERROR] [esx_inventoryhud_glovebox] An error happens for query "INSERT INTO glovebox_inventory(plate,data,owned) VALUES (?,'{}',?) : [" YUY405 ",false]": ER_DUP_ENTRY: Duplicate entry ' YUY405 ' for key 'plate'

[MariaDB:10.4.14-MariaDB] [ERROR] [esx_inventoryhud_trunk] An error happens for query "INSERT INTO trunk_inventory(plate,data,owned) VALUES (?,'{}',?) : [" YUY405 ",false]": ER_DUP_ENTRY: Duplicate entry ' YUY405 ' for key 'plate'

**Comment by Borea** [comment]
same error for me

**Comment by Dokman** [comment]
idk why, but is a problem with the json and the code, that always try to insert again an inventory if it's not created, so it means that always will do a duplicate

```
function MakeDataStore(plate)
	local data = {}
	local owned = getOwnedVehicle(plate)
	local dataStore = CreateDataStore(plate, owned, data)
	SharedDataStores[plate] = dataStore
	MySQL.Async.execute(
	"INSERT INTO glovebox_inventory(plate,data,owned) VALUES (@plate,'{}',@owned)",
		{
			["@plate"] = plate,
			["@owned"] = owned
		}
	)
	loadInvent(plate)
end
```

this is the bomb in the code, the code is calling this all time.

**Comment by Dokman** [comment]
i will test it deeply, if i can fix it, i will do a pull request

**Comment by ghost** [comment]
same problem.

**Comment by RuisSoftware** [comment]
Should be fixed in the last updates (increase databse identifier to varchar(60))

**Comment by alvinveroy** [comment]
Apparently, what causes this bug to do a Duplicate entry was when a call to get the glovebox inventory weight also does an insert query to the database. The ```TriggerEvent("dp_inventory_glovebox:GetSharedDataStoreGlovebox", plate, function(store)``` is the culprit. This needs to be changed into selecting the database instead of doing insert to get the total inventory weight.

```
function getTotalInventoryWeightGlovebox(plate)
	local total
	TriggerEvent("dp_inventory_glovebox:GetSharedDataStoreGlovebox", plate, function(store)
		local W_weapons = getInventoryWeightGlovebox(store.get("weapons") or {})
		local W_coffres = getInventoryWeightGlovebox(store.get("coffres") or {})
		local W_blackMoney = 0
		local blackAccount = (store.get("black_money")) or 0
		if blackAccount ~= 0 then
			W_blackMoney = blackAccount[1].amount / 10
		end
		local W_cashMoney = 0
		local cashAccount = (store.get("money")) or 0
		if cashAccount ~= 0 then
			W_cashMoney = cashAccount[1].amount / 10
		end
		total = W_weapons + W_coffres + W_blackMoney + W_cashMoney
		end)
	return total
end
```
Notice the TriggerEvent calls the following event handler below:

```
AddEventHandler("dp_inventory_glovebox:GetSharedDataStoreGlovebox", function(plate, cb)
	cb(GetSharedDataStoreGlovebox(plate))
end)
```

which calls this function:
```
function GetSharedDataStoreGlovebox(plate)
	if SharedDataStores[plate] == nil then
		MakeDataStoreGlovebox(plate)
	end
	return SharedDataStores[plate]
end
```
which leads to:

```
function MakeDataStoreGlovebox(plate)
	local data = {}
	local owned = getOwnedVehicle(plate)
	local dataStore = CreateDataStoreGlovebox(plate, owned, data)
	SharedDataStores[plate] = dataStore
	MySQL.Async.execute("INSERT INTO glovebox_inventory(plate,data,owned) VALUES (@plate,'{}',@owned)", {
		["@plate"] = plate,
		["@owned"] = owned
	})
	loadInventGloveboxGlovebox(plate)
end
```
