### ISSUE TITLE
How to configure a new vehicle category with its own capacity?

### ISSUE THREAD

**Issue by Valkyrionas** [dutchplayers/FiveM-Resources#179]
Hello Folks, great work on the Script till now, it works everything fine but I would like to add other Vehicle Categories (because I added some categories as alternatives/electrics/pick-ups/oldtimer and I wanted to give them each different values of the capacity, therefore now all the addoncars im using now in these categories, got a default value of 50 which is half of the inventory capacity and really to low... you know how I could change this? I see in the config.lua there are the categories located (default ones) with an number in brackets [1] to [21] but where can I define these or even add then ? as example [22] XXX = oldies (for Oldtimers) etc, in the js folder I even don't see the arrays or the defined code entries... where are them? :(

Thanks for any useful help on this isssue...

**Comment by RuisSoftware** [comment]
No idea, thats related to GTA core game
