### ISSUE TITLE
Hotkey bar glitch

### ISSUE THREAD

**Issue by Bragh** [dutchplayers/FiveM-Resources#180]
**Describe the bug**
When you hotkey a weapon of any kind, press the hotkey number that corresponds to that item it will cycle through the weapon in the spot and weapons not in your inventory instead of putting the item away.

**Comment by bashon1** [comment]
> **Describe the bug**
> When you hotkey a weapon of any kind, press the hotkey number that corresponds to that item it will cycle through the weapon in the spot and weapons not in your inventory instead of putting the item away.

have some issue 
did u find any way to fix it?

**Comment by RuisSoftware** [comment]
I dont have this.

More people?

**Comment by ElecTwix** [comment]
Same

**Comment by RuisSoftware** [comment]
Send some more info

**Comment by RuisSoftware** [comment]
what is your es_extended fxmanifest version?

**Comment by ElecTwix** [comment]
I just fix it. it is my bad. Sorry about it.

**Comment by Jabelius** [comment]
@ElecTwix what about sharing that info of yours?

**Comment by ElecTwix** [comment]
@Jabelius that was caused because of my base I just write mine for my server because of that.

**Comment by TopgunMarvick** [comment]
same problem here. Use 1.2 lastest
