### ISSUE TITLE
Hotkey bar is not working for weapon

### ISSUE THREAD

**Issue by tonibanks** [dutchplayers/FiveM-Resources#181]
Having issue weapon hotkey bar for weapon, weapons is not registering on hotkey 1 to 5 i don't know why.

**Comment by bashon1** [comment]
> Having issue weapon hotkey bar for weapon, weapons is not registering on hotkey 1 to 5 i don't know why.

have some issue 
did u find any way to fix it?

**Comment by RuisSoftware** [comment]
Use latest update
