### ISSUE TITLE
Don't show weight and plate in glowbox and trunk inventory

### ISSUE THREAD

**Issue by wolvherin78** [dutchplayers/FiveM-Resources#186]
Don't show weight and plate into trunk and glovebox inventory

**Comment by shyricaus** [comment]
mine is also like this, managed to solve

**Comment by shyricaus** [comment]
![image](https://user-images.githubusercontent.com/28937245/97122653-26047100-1706-11eb-964a-9aa058f305c4.png)

I also have these errors when I open the glove box

**Comment by RuisSoftware** [comment]
It does now
