### ISSUE TITLE
Invalid ref attempt

### ISSUE THREAD

**Issue by unknowndeira** [dutchplayers/FiveM-Resources#194]
When I connected the server, console says "Invalid ref attempt 1-2-3-4-5-6+" and extended memory is blowing up, my fps getting down, hope you can fix or help.

**Comment by RuisSoftware** [comment]
Never heard about.

Please provide more information

**Comment by unknowndeira** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/40323418/97162369-2ba69900-1790-11eb-81fd-e7694e2fba8a.png)
like this

**Comment by RuisSoftware** [comment]
How can we reproduce this?

**Comment by unknowndeira** [comment]
It happen randomly, I actually don't know how to do it.

**Comment by ulasdemirci0** [comment]
I solved this issue.
Change the "glovebox_inventory" and "trunk_inventory" table names to "inventory_glovebox" and "inventory_trunk". 

@theDeira 
@dutchplayers

**Comment by unknowndeira** [comment]
I will try and hope it will fix the issue.
Thanks btw.

**Comment by RuisSoftware** [comment]
Oh, oke

**Comment by fucekar** [comment]
i have same issuse something randomly do for all and all players got drop fps
