### ISSUE TITLE
DPFramework

### ISSUE THREAD

**Issue by JeremyPBang** [dutchplayers/FiveM-Resources#195]
Hello,

i get an error because i need the DP_Framework.

**Comment by JeremyPBang** [comment]
and this error

https://prnt.sc/v6zfhy

**Comment by unknowndeira** [comment]
try this 
`function MakeDataStore(plate)
    local data = {}
    local owned = getOwnedVehicle(plate)
    local dataStore = CreateDataStore(plate, owned, data)
    SharedDataStores[plate] = dataStore
    MySQL.Async.fetchAll('SELECT * FROM trunk_inventory WHERE plate = @plate', {
        ["@plate"] = plate
    }, function(result)
        if result[1] == nil then
          MySQL.Async.execute("INSERT INTO trunk_inventory(plate,data,owned) VALUES (@plate,'{}',@owned)",{
              ["@plate"] = plate,
              ["@owned"] = owned
            })
        end
    end)
    loadInvent(plate)
end`

**Comment by RuisSoftware** [comment]
Download latest
