### ISSUE TITLE
My Users can't use the Hotkeys or can't use any weapons from the inv.

### ISSUE THREAD

**Issue by GiNside97** [dutchplayers/FiveM-Resources#198]
Hey Guys, my User's can't use Weapons from the Hotkeys, in General they can't use weapons.

Just installed the new Build on ESX 1.2

**Comment by RuisSoftware** [comment]
All weapons in your database?

Did you buy the weapon or /giveitem?

And download latest master

**Comment by GiNside97** [comment]
I've tested all Weapons Buying&Giving but no Chance.

okay is there a fix for it? bc I've downloaded yesterday the last master from u guys.

**Comment by GiNside97** [comment]
Just reinstalled the new 3.3.9 from u guys but....
Getting this error:

https://prnt.sc/v9fv31

mythic_notfiy 1.1.0 is installed

Weapon Hotkey Issue ongoing!

**Comment by RuisSoftware** [comment]
Can you double confirm that your es_extended fxmanifest version is 1.2

**Comment by RuisSoftware** [comment]
Also, you do not have the correct mythic version installed

Soon we stop with mythic and only use t-notify

**Comment by GiNside97** [comment]
which version do I need?
And Yes my fxmanifest is 1.2.0

**Comment by GiNside97** [comment]
UPDATE: Now I'm getting: ex_extended/server/main.lua417: Attempt to index a nil value if I'm pressing 1 for example for an weapon

Which is this function:

```
RegisterNetEvent('esx:useItem')
AddEventHandler('esx:useItem', function(itemName)
	local xPlayer = ESX.GetPlayerFromId(source)
	local count = xPlayer.getInventoryItem(itemName).count

	if count > 0 then
		ESX.UseItem(source, itemName)
	else
		xPlayer.showNotification(_U('act_imp'))
	end
end)
```

what to do?

**Comment by GiNside97** [comment]
#solved 
Just added ammunition Table and now it's working.
The Table was not added by himself as injecting the sql file, had to manual add it
