### ISSUE TITLE
Shops nil value (field job)

### ISSUE THREAD

**Issue by iiAlphaWolf** [dutchplayers/FiveM-Resources#201]
When i join the server and my player is loaded i get an error in F8.
Im using ESX 1.2 and latest update from inventoryhud.
![image](https://user-images.githubusercontent.com/30497126/97760112-b83fb700-1b02-11eb-846f-f0c363942f65.png)
While i installed the scripts i used the wiki, this started with the last update.

Any idea why this is?

**Comment by GiNside97** [comment]
have the same issue

**Comment by iiAlphaWolf** [comment]
Idk if it has anything to do with it but after a while randomly the shops stop working too, im trying to find out if there is a reason. After eash automated restart from txAdmin the shops stop working.

If i ensure the script while im in game it will fix the problem until next restart..

**Comment by lilwesyy** [comment]
I have fixed the problem by replacing the shop.lua with the 3.3.9 👍

**Comment by iiAlphaWolf** [comment]
> I have fixed the problem by replacing the shop.lua with the 3.3.9 👍

Yeah ur right, i just tried it and it solved the problem, thanks! But why is this though

**Comment by lilwesyy** [comment]
> > I have fixed the problem by replacing the shop.lua with the 3.3.9 👍
> 
> Yeah ur right, i just tried it and it solved the problem, thanks! But why is this though

this is the problem 
		beroep = ESX.GetPlayerData().job.name
		gradatie = ESX.GetPlayerData().job.grade

**Comment by lilwesyy** [comment]
it should be a short way to call the same thing over time 👯

**Comment by RuisSoftware** [comment]
Reverted in 3.4.4
