### ISSUE TITLE
Question: Performance

### ISSUE THREAD

**Issue by benzon** [dutchplayers/FiveM-Resources#202]
This aint a bug report but a question.

How is this performing on server with high amount of slots?

**Comment by RuisSoftware** [comment]
Resources like this are NOT for large server 64> players. 

Or you have a BEAST machine with 16 threads 4.6GHz and 3000mhz RAM. Then you can hit 100 players.

**Comment by RuisSoftware** [comment]
I have to say that the latest updates are not performance updates...
