### ISSUE TITLE
Giving money with esx 1.1

### ISSUE THREAD

**Issue by Nikouw36** [dutchplayers/FiveM-Resources#204]
**Describe the bug**
Giving money doesn't work. How i can fix it?

**To Reproduce**
1. Give money to a player

**Expected behavior**
Giving the money

**Screenshots**
https://i.imgur.com/jN3ZBnN.gif
**ESX version:**
 - Version 1.1

**Additional context**
I was able to give money in my old version of the inventoryhud 

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
![afbeelding](https://user-images.githubusercontent.com/53178920/98130037-1b8e6800-1eba-11eb-9076-3087012477d5.png)

**Comment by Nikouw36** [comment]
![image](https://user-images.githubusercontent.com/5896756/98130292-5ee8d680-1eba-11eb-99b5-45b60bf3d282.png)
For the ESX 1.1 people:

for fixing it replace in client/main.lua:
```
	if data.item.type == "item_money" then
				TriggerServerEvent("esx:giveInventoryItem", data.player, "item_account2", "money", count)
			else
				TriggerServerEvent("esx:giveInventoryItem", data.player, data.item.type, data.item.name, count)
			end
```
to
            `TriggerServerEvent("esx:giveInventoryItem", data.player, data.item.type, data.item.name, count)`
