### ISSUE TITLE
After closing you can no longer move or do other things

### ISSUE THREAD

**Issue by Achim-Sommer** [dutchplayers/FiveM-Resources#205]
**Describe the bug**
I open the menu with F2 and close it again with F2 after that you can't do anything else in the game. No errors in the console and the mouse pointer remains in the image

**ESX version:**
 - 1.2

**Followed Wiki**
Yes

**Comment by ulasdemirci0** [comment]
install optional resources.
Wiki isn't useful it have to been updated.

Check console when resource started it prints needed sources. b1g_notify doesn't work you can remove this.
I cant remember but t-Notify is needed for this.

**Comment by Achim-Sommer** [comment]
> install optional resources.
> Wiki isn't useful it have to been updated.
> 
> Check console when resource started it prints needed sources. b1g_notify doesn't work you can remove this.
> I cant remember but t-Notify is needed for this.

I have t-Notify without this it will not start

**Comment by RuisSoftware** [comment]
Foldername MUST be esx_inventoryhud
