### ISSUE TITLE
Weapons not getting pulled out with hotbar

### ISSUE THREAD

**Issue by FBFezz** [dutchplayers/FiveM-Resources#207]
**Describe the bug**
If a weapon is in the hotbar and you try take it out it says action impossible

**To Reproduce**
1. Put weapon in hotbar
2. try equip the weapon using hotbar
3. See error

**Expected behavior**
Weapon is supposed to be pulled out

**Screenshots**
N/A

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by shyricaus** [comment]
that and why didn't you turn your weapons into items

**Comment by shyricaus** [comment]
you have to run sql, which comes in the script

**Comment by FBFezz** [comment]
I have sql'd them, So i need to give people weapons as items? Thats going to break so much stuff and if its done like that it makes no sense at all

**Comment by RuisSoftware** [comment]
You are free to use all version out there.

In latest version we dont use weapons as weapons. A weapon is an item.

**Comment by FBFezz** [comment]
Would that not cause issues with other scripts like property or vault?

**Comment by FBFezz** [comment]
And how would the ammo system work?

**Comment by RuisSoftware** [comment]
Nope, scripts are al using it as item. Do not use /giveweapon or default esx armory.

Ammo check database file for ammunition_ items. Put them in hotbar and use thm ;)

**Comment by FBFezz** [comment]
ahh ok thank you, got it working, Keep up the great work :)
