### ISSUE TITLE
couldn't find resource esx_inventoryhud

### ISSUE THREAD

**Issue by prouargegamer** [dutchplayers/FiveM-Resources#208]
**Describe the bug**
when start the bat file it say couldnt find resource esx_inventoryhud and why?

**To Reproduce**

**Expected behavior**
couldnt find resource esx_inventoryhud when start bat file.

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/73350738/98408133-b4e68700-203e-11eb-8e1d-9643121323a0.png)

**ESX version:**
 - Version [e.g. 1.2]

**Additional context**

**Followed Wiki**
Yes/No
yes

**Comment by RuisSoftware** [comment]
rename folder to esx_inventoryhud and start esx_inventoryhud

**Comment by prouargegamer** [comment]
ive done that but thank you!
