### ISSUE TITLE
frozen character

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#209]
Character movements freeze after closing inventory. As a result, the mouse is still on the screen as if the inventory is still open.
Even if I try to open the inventory again, it is not possible. F8 and console do not have any errors.

ESX ver. 1.2

**Comment by prouargegamer** [comment]
i cant even get esx_inventoryhud to open when press the .bat file,do you know how to properly install esx_inventoryhud?

**Comment by RuisSoftware** [comment]
rename folder name to esx_inventoryhud

**Comment by prouargegamer** [comment]
ive renamed and closed,i just found out i was using esx_inventory hud 2.4
so i downgraded to 1.1 and it worked.
