### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Danielfivem1** [dutchplayers/FiveM-Resources#21]
Duplicate column name 'price' . Help

**Comment by ClicheUsername** [comment]
Remove this from your SQL file before you run it:

ALTER TABLE `items`
	ADD COLUMN `price` int(11) NOT NULL DEFAULT 0
;

**Comment by Danielfivem1** [comment]
ERROR 1062 (23000) at line 23: Duplicate entry 'WEAPON_FLASHLIGHT' for key 'PRIMARY' 
;/

**Comment by Danielfivem1** [comment]
Bro can we connect on discord?

**Comment by RuisSoftware** [comment]
You can contact Dutch Players https://www.dutch-players.nl/go/discord/

**Comment by Danielfivem1** [comment]
I connect u
