### ISSUE TITLE
Stuck When Close The Inventory

### ISSUE THREAD

**Issue by ChloeNavae** [dutchplayers/FiveM-Resources#210]
**Describe the bug**
When i try to close the inventory the pointer(mouse) stuck..... and i cant do anything

**Comment by bashon1** [comment]
Some problem

**Comment by RuisSoftware** [comment]
Change the folder name to esx_inventoryhud

**Comment by ChloeNavae** [comment]
> 
> 
> Change the folder name to esx_inventoryhud

its work againd.... but i cant use quick slot for weapon... its says "Actions Imposibble"
And There's a error in extendedmode

**Comment by RuisSoftware** [comment]
Read title of readme.
