### ISSUE TITLE
Purchasing Weapons/Storing them in trunk issue

### ISSUE THREAD

**Issue by FakeItalianMan** [dutchplayers/FiveM-Resources#211]
When I add weapons into a shop and I go to purchase it it is counting it as an item and not an actual weapon in my inventory also cant store them in the trunk or glovebox how can I fix this? Thank you.

**Comment by ulasdemirci0** [comment]
Firstly backup your database then run this file i edited the original sql file and fixed some wrong syntax
[dpFix.zip](https://github.com/dutchplayers/DP_Inventaris/files/5506248/dpFix.zip)

**Comment by RuisSoftware** [comment]
rly............

**Comment by FakeItalianMan** [comment]
> rly............

Why you saying rly? It's not working for me and am trying to get some support because when I add weapons to the store that is integrated with the inventoryhud I go to purchase the gun and it only shows up as an item and not an actual weapon.

**Comment by RuisSoftware** [comment]
Were is the issue template?

What is your es_extended fxaminfest version?
Latest master branch inventory?
Have all dependencies from inventory fxmanifest?
Have you check database? Items in DB?
Never spawn weapons with /giveweapon
Any error in F8 or server console?

**Comment by FakeItalianMan** [comment]
I am an Idiot, lol Sorry my bad I figured it out. Thank you.
