### ISSUE TITLE
Controls locked after closing the inventory

### ISSUE THREAD

**Issue by pablo-rico** [dutchplayers/FiveM-Resources#212]
**Describe the bug**
The controls are locked when you close the inventory, the interface disapears but the mouse is still visible and the keyboard is locked

**To Reproduce**
1. Go to 'the inventory'
2. Click on 'F2 or ESC to exit the interface'

**Expected behavior**
The controls should unlock when the interface disapears

**ESX version:**
 - Version 1.2 final

**Followed Wiki**
Yes

**Comment by ghost** [comment]
I get the same issue as above

**Comment by RuisSoftware** [comment]
rename folder to esx_inventoryhud
