### ISSUE TITLE
Ammo Count not showing in inventory.

### ISSUE THREAD

**Issue by ElecTwix** [dutchplayers/FiveM-Resources#213]
**Describe the bug**
Can't see ammo count in the inventory

**To Reproduce**
1. Press 'F2'
2. Give item 'weapon_pistol'
3. Put it in the slots
4. You can't see ammo count

**Screenshots**
[ScreenShot](https://steamuserimages-a.akamaihd.net/ugc/1695003942561748978/FB02B30B49AA287FB52D99D7A4EBBE80BCC515D3/)

**ESX version:**
 - Version ESX 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
True. Planned feature.
