### ISSUE TITLE
Esx_menu_default

### ISSUE THREAD

**Issue by prouargegamer** [dutchplayers/FiveM-Resources#214]
**Describe the bug**
uncaught typeErroe: cnnot read property 'scrollinvtoiew' of undefined (esx_menu_default/html/js/app.js:69)

**To Reproduce**

uncaught typeErroe: cnnot read property 'scrollinvtoiew' of undefined (esx_menu_default/html/js/app.js:69)

**Expected behavior**

When go to any property it say that error code above in console

**Screenshots**

![Untitled-1.png](https://user-images.githubusercontent.com/73350738/98596815-004e9e80-22a6-11eb-8c30-f9c1e51023d7.png)

**ESX version:**
 - Version [e.g. 1.2]
Yes

**Additional context**

**Followed Wiki**
Yes/No
Yes

**Comment by RuisSoftware** [comment]
Why do you think that this is relevant to our inventory?

**Comment by prouargegamer** [comment]
i thought you can help me

**Comment by RuisSoftware** [comment]
You can visit www.dutch-players.nl/joindiscord for custom support

**Comment by prouargegamer** [comment]
ok
