### ISSUE TITLE
Bug: Picked up items will go into weapon wheel instead of inventory system

### ISSUE THREAD

**Issue by Chronic-Reflexes** [dutchplayers/FiveM-Resources#216]
**Describe the bug**
Any picked up object be it a weapon from a dead cop, Or jerry cans bought from legacy fuel. they go into the weapon wheel instead of the inventory

**To Reproduce**

1. Pickup weapon/item
2. weapon/item will go into the weaponwheel, Locking the weapon in the players hand

**Expected behavior**

When picking up a weapon/item, It should display in the inventory system

**ESX version:**

 - 1.2-final

**Additional context**

pls fix

**Followed Wiki**
yes

**Comment by RuisSoftware** [comment]
You should use ESX.CreatePickup instead of the default drops.

**Comment by RuisSoftware** [comment]
Hi, use version Inventory >= 1.2.1 and read readme for support
