### ISSUE TITLE
Inventory not closing!

### ISSUE THREAD

**Issue by MDJHShovon** [dutchplayers/FiveM-Resources#219]
When I try to open the inventory, it works perfectly, but when I try to close the inventory, it's not closing. It just stuck

**Comment by rasodpt** [comment]
You probably changed the script name, it must be esx_inventoryhud for everything to work :)

**Comment by MDJHShovon** [comment]
Yeah. I made this mistake. Renamed the resource name to esx_inventoryhud and it's working perfectly! Thank you so much
