### ISSUE TITLE
Can't use the bag inventory!

### ISSUE THREAD

**Issue by MDJHShovon** [dutchplayers/FiveM-Resources#220]
I can't use the bag inventory. It's given me [this](https://imgur.com/Tl1CVPU) error at the time of first registration 
And when I took a bag and try to open that bag, it's giving me [this](https://imgur.com/R2HRIXO) error 

Please help me to fix this problem

I am using es_extended 1.2 final

**Comment by RuisSoftware** [comment]
I think it has something to do with esx_skin, but not sure. I will take a look if i can fix it on our end, but check you esx_clotheshop and esx_skin also

**Comment by MDJHShovon** [comment]
Thank you so much. But the issue isn't happening on the latest update. But facing a new issue! Can't close the inventory after the latest update

**Comment by RuisSoftware** [comment]
Be sure to rename the resource foldrname to DP_Inventory

**Comment by MDJHShovon** [comment]
I renamed it to DP_Inventory. But still the same. Can't close the inventory, also can't give, drop or use any item
