### ISSUE TITLE
Mouse Cursor Still In Monitor

### ISSUE THREAD

**Issue by jakaagustian** [dutchplayers/FiveM-Resources#221]
**Describe the bug**
When i close inventory with f2, mouse curser still in monitor...
please help..?

**ESX version:**
 - Version12 final

**Followed Wiki**
Yes

**Comment by MDJHShovon** [comment]
Rename the inventory to esx_inventoryhud

**Comment by RuisSoftware** [comment]
We fixed the structure in the repo
