### ISSUE TITLE
Facing the inventory not closing issue again!

### ISSUE THREAD

**Issue by MDJHShovon** [dutchplayers/FiveM-Resources#222]
After using the latest update my inventory again stucks. Can't move or can't do anything if I open the inventory one time. I tried to use the inventory as esx_inventoryhud also as DP_Inventories. Every time the same result. I also used the recommended MySQL-async

**Comment by RuisSoftware** [comment]
It is 'DP_Inventory' now :) Its definitive now! :')

**Comment by MDJHShovon** [comment]
Ok.Will try with that name also. Thank you

**Comment by MDJHShovon** [comment]
Still facing the same issue! It's not closing! It's just stuck! :(

**Comment by GFA-SkyRanger** [comment]
Same issue here.
i was looking for an inventory-plugin which is working, but this cannot be closed.
i upgraded my es_extended from 1.1 to 1.2, just for this addon.
