### ISSUE TITLE
Trunk Inventory Open issue

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#225]
**Describe the bug**

When I try to open a trunk, it doesn't open. The normal inventory and glove compartment work.

I have to say, however, that it worked a few minutes ago, and I wanted to test whether guns could be tucked in and it did. Then the following message came in the F8 console

**To Reproduce**
1. Go to 'Trunk'
2. Pull a gun into the trunk
3. Run away / close the trunk

**Screenshots**
http://i.epvpimg.com/jN0Bdab.png.

** More INFO ***
main.lua:234

`-- Disable controls while GUI open
Citizen.CreateThread(function()
    while true do
        if isDoingAction then
            if not isAnim then
                if mythic_action.animation ~= nil then
                    if mythic_action.animation.task ~= nil then
                        TaskStartScenarioInPlace(PlayerPedId(), mythic_action.animation.task, 0, true)
                    elseif mythic_action.animation.animDict ~= nil and mythic_action.animation.anim ~= nil then
                        if mythic_action.animation.flags == nil then
                            mythic_action.animation.flags = 1
                        end`

**ESX version:**
 -  version '1.2.0'

**Followed Wiki**
Yes

**Comment by bashon1** [comment]
i think your problem is
 you don't have the proper mythic_notfiy, either get the updated mythic_notify or change every SendAlert to DoHudText
