### ISSUE TITLE
addon weapon can not be use

### ISSUE THREAD

**Issue by bashon1** [dutchplayers/FiveM-Resources#227]
Hello
i add addon weapon and added it on config file
now when i try use it not wokring showing me this error
SCRIPT ERROR: @es_extended/server/functions.lua:247: attempt to call a nil value (field '?')

**Comment by RuisSoftware** [comment]
Can you send the addon to my Discord, ill test and fix if not working

**Comment by knightsir** [comment]
i am having the same issue still but on #417
https://gyazo.com/f169fbe92f0b9a69c8226fc49e90b60a

**Comment by JSanchezFDZ** [comment]
Have same issue

**Comment by RuisSoftware** [comment]
Can someone send us an addon weapon on Discord? We will check it out

**Comment by bashon1** [comment]
> Can someone send us an addon weapon on Discord? We will check it out

i sent you some week ago

**Comment by bashon1** [comment]
addon weapon still not work
