### ISSUE TITLE
Bug: weapons can be used from other scripts for weapons

### ISSUE THREAD

**Issue by xZUAx** [dutchplayers/FiveM-Resources#228]
**Describe the bug**
When I add a custom black market in. When I buy a weapon it's dose not let me pull out the weapon only says action impossible.

**To Reproduce**
1. Go to 'if you using any job or script that give you a weapon like police armor'
2. Click on 'Buy a weapon and then open F2 '
3. Scroll down to 'Drag weapon to your number 1 slot and you should seee error'

**Expected behavior**.
What I found is if you using any script that gives the player a weapon out side of the Hud it will not work add is dose not save to the SQL but to the weapon wheel

**Screenshots**.
https://cdn.discordapp.com/attachments/564156825382158348/781575615212027934/unknown.png

**ESX version:**
 - Version [ 1.2]

**Additional context**
N/A

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Buy weapons as item.
