### ISSUE TITLE
Shared Motel items between kashacters

### ISSUE THREAD

**Issue by maguhd** [dutchplayers/FiveM-Resources#230]
**Describe the bug**
Using the inventory + motels + kashacters. 
1. If I rent a motel room, another player can still rent it. 
2. If I create another char using kashacters and I rent a room, the items apear on all characters, items are not individual.

**ESX version:**
 - Version [1.2]

**Followed Wiki**
Yes

https://www.dutch-players.nl/joindiscord

**Comment by ianvalls90** [comment]
that's kashacters issue, not this script's fault.

**Comment by RuisSoftware** [comment]
This script is not made for multichar, but it's a planned feature. No date.
