### ISSUE TITLE
Give Item to player  no ID option

### ISSUE THREAD

**Issue by DaBay93** [dutchplayers/FiveM-Resources#231]
I tried to give the item to another player and there is no player ID option.
If there is more than one player it will be randomly assigned.

**Comment by RuisSoftware** [comment]
Randomly = closest target

**Comment by RuisSoftware** [comment]
But if more people want the default esx_inventoryhud select player option we can add it in

**Comment by DaBay93** [comment]
OK, thanks.

I have made it,

Now, I want to make "WEAPON_PETROLCAN" count in the number of ammo count, how do I?
I have tried it and the results still display a count "1", if I change to addWeapon it won't to use.

**Comment by SteveBaggins** [comment]
> But if more people want the default esx_inventoryhud select player option we can add it in

Would be nice to maybe have an option, some people in my community asked for it back just to be sure they know whos getting what.

**Comment by colonelnl** [comment]
how can i fix it ? select player id ?
