### ISSUE TITLE
GLOVE - TRUNK problem

### ISSUE THREAD

**Issue by LySoon** [dutchplayers/FiveM-Resources#235]
it works as it should be, but every time it tries to re-create to database.

**Comment by LySoon** [comment]
![image](https://user-images.githubusercontent.com/49767982/102714187-017bde00-42de-11eb-87be-60be1d32e1b3.png)

**Comment by RuisSoftware** [comment]
Thank you for reporting ;)

**Comment by LySoon** [comment]
you're welcome ^^

**Comment by RuisSoftware** [comment]
Can you try the latest master branch update?

https://github.com/dutchplayers/FiveM-Resources/commit/26246d576d72eb8d2ecb1b59131225986901e94e

**Comment by LySoon** [comment]
Yea, thank you its working just fine right now.
great work <3

**Comment by LySoon** [comment]
also i would love to join your discord if there is one?

**Comment by RuisSoftware** [comment]
Yes! http://www.dutch-players.nl/joindiscord

**Comment by LySoon** [comment]
im in <3
