### ISSUE TITLE
Attachment problem.

### ISSUE THREAD

**Issue by MadLad1Clip** [dutchplayers/FiveM-Resources#238]
**Describe the bug**
Ok so problems with the attachment, when adding to the first gun no problem but after that adding to a 2nd gun is creating the error.

[ERROR] [MySQL] [DP_Inventory] An error happens on MySQL for query "INSERT INTO ammunition (owner, hash, count, attach, weapon_id, original_owner) VALUES ('license:*********************************************', 453432689, 0, '[]', 'ARkMHEDqdbNDMSjoViCKWeHAbvaWLI250123374610846441944509887023', 'license:************************************')": ER_DUP_ENTRY: Duplicate entry 'license:**************************************' for key 'owner'
 

**To Reproduce**
1. Add attachments to one gun
2.  Change guns and attampt to add attachments to that gun.

**Expected behavior**
When you attempt to add the attachment to the 2nd gun it wont save when u put the gun away and then throws the error to the database. 
[ERROR] [MySQL] [DP_Inventory] An error happens on MySQL for query "INSERT INTO ammunition (owner, hash, count, attach, weapon_id, original_owner) VALUES ('license:*********************************************', 453432689, 0, '[]', 'ARkMHEDqdbNDMSjoViCKWeHAbvaWLI250123374610846441944509887023', 'license:************************************')": ER_DUP_ENTRY: Duplicate entry 'license:**************************************' for key 'owner'

**ESX version:**
 - Version 1.2

**Followed Wiki**
Yes

**Comment by RuisSoftware** [comment]
Hi can you try https://github.com/dutchplayers/FiveM-Resources/commit/dac2e3ba255ddcd5a7567731074ae09174d89814

**Comment by MadLad1Clip** [comment]
It has not fixed the problem now it replaced the last database entry with the other weapon and the first weapon no longer has its attachments.

**Comment by RuisSoftware** [comment]
Oh, oke i will take a look into it asap

**Comment by MadLad1Clip** [comment]
Ok i am guessing the problem is that its not matching the weapon_id and owner if same then make new entry.

**Comment by MadLad1Clip** [comment]
The problem also runs over the ammo system when adding ammo to a 2nd gun getting the same errors.

**Comment by RuisSoftware** [comment]
Oke thank you. The attachement update is pushed yesterday for the first time ;)

We will look into the problems that is causing and will fix it. Stay tuned!

**Comment by MadLad1Clip** [comment]
Yeah no worries at all, loving what u have done so far. Keep up the good work.
