### ISSUE TITLE
esx_property

### ISSUE THREAD

**Issue by MadLad1Clip** [dutchplayers/FiveM-Resources#239]
How do i get ur system to work with esx_property? I get this error
![image](https://user-images.githubusercontent.com/5630104/102722931-80800f00-42fc-11eb-8096-f4c0da3b3989.png)

I have changed the trigger to call this inventroy.
TriggerEvent("DP_Inventory:openPropertyInventory", inventory)

**Comment by RuisSoftware** [comment]
Your function must like:
```lua
function OpenPropertyInventoryMenu(property, owner)
	ESX.TriggerServerCallback("esx_property:getPropertyInventory", function(inventory)
		TriggerEvent("DP_Inventory:openPropertyInventory", inventory)
	end, owner)
end
```
Be sure to upload 

```sql
INSERT INTO `addon_account` (name, label, shared) VALUES
  ('property_money','Cash',0),
  ('property_black_money','Black Money',0)
;
```

**Comment by MadLad1Clip** [comment]
Yes that is how mine is setup.

**Comment by RuisSoftware** [comment]
Can you confirm if you have done this
```sql
INSERT INTO `addon_account` (name, label, shared) VALUES
  ('property_money','Cash',0),
  ('property_black_money','Black Money',0)
;
```

Your error tells that it does not get money. Money = nil. So it might be that its just not in the database.

Be sure to restart the server after this SQL injection

**Comment by MadLad1Clip** [comment]
Yeah i did set that up. Ill run over it all again tomorrow and make sure i didnt miss anything else.

**Comment by MadLad1Clip** [comment]
yeah i am still getting the error, i need to remove the bignotify that might be why as i dont use that system

![image](https://user-images.githubusercontent.com/5630104/102917641-7df8f300-447d-11eb-85de-350979d4a115.png)

**Comment by AgenChicken24** [comment]
can you show that line and also it seems that you don't have the right version of the b1g notify or an old one

**Comment by MadLad1Clip** [comment]
i dont use b1g ill have to change that to the system i use

**Comment by MadLad1Clip** [comment]
![image](https://user-images.githubusercontent.com/5630104/102919519-eac1bc80-4480-11eb-8a38-933769f156d1.png)

**Comment by AgenChicken24** [comment]
Alright try to do it right this: 
```lua
if money ~= nil then
  if money > 0 then
    accountData = {
	    label = _U("cash"),
	    count = money,
	    type = "item_money",
	    name = "cash",
	    usable = false,
	    rare = false,
	    weight = 0,
	    canRemove = false
    }
    table.insert(items, accountData)
  end
end

**Comment by MadLad1Clip** [comment]
ok before i do i am also getting this in the console. 
![image](https://user-images.githubusercontent.com/5630104/102919821-73d8f380-4481-11eb-84d8-6e13fe0011b0.png)

**Comment by MadLad1Clip** [comment]
also this problem when adding a bag
![image](https://user-images.githubusercontent.com/5630104/102920705-180f6a00-4483-11eb-818c-35ad678b67fc.png)

**Comment by MadLad1Clip** [comment]
This is the addoninventroy script
![image](https://user-images.githubusercontent.com/5630104/102921284-0a0e1900-4484-11eb-8e83-4ed4265c3021.png)

**Comment by MadLad1Clip** [comment]
Also when adding a bag it is resetting my skin and when relogging i am invisable setting everything to 0.

{"torso_1":0,"mask_1":0,"blush_3":0,"arms_2":0,"hair_color_1":0,"blush_2":0,"shoes_1":0,"torso_2":0,"makeup_3":0,"eyebrows_4":0,"lipstick_4":0,"ears_1":-1,"bproof_2":0,"beard_1":0,"watches_1":-1,"moles_1":0,"blemishes_2":0,"bracelets_2":0,"pants_1":0,"hair_1":0,"makeup_4":0,"makeup_2":0,"beard_2":0,"bags_2":0,"moles_2":0,"eye_color":0,"ears_2":0,"hair_color_2":0,"bodyb_1":0,"chest_3":0,"bags_1":45,"pants_2":0,"bproof_1":0,"chest_1":0,"age_2":0,"shoes_2":0,"eyebrows_3":0,"lipstick_3":0,"glasses_1":0,"sun_2":0,"blush_1":0,"makeup_1":0,"sun_1":0,"tshirt_1":0,"bracelets_1":-1,"skin":0,"chain_1":0,"watches_2":0,"beard_4":0,"bodyb_2":0,"eyebrows_2":0,"arms":0,"complexion_2":0,"lipstick_1":0,"helmet_2":0,"glasses_2":0,"complexion_1":0,"decals_1":0,"blemishes_1":0,"decals_2":0,"hair_2":0,"eyebrows_1":0,"beard_3":0,"mask_2":0,"helmet_1":-1,"chest_2":0,"age_1":0,"chain_2":0,"lipstick_2":0,"sex":0,"face":0,"tshirt_2":0}

**Comment by MadLad1Clip** [comment]
I have fixed the problem with the bag.

![image](https://user-images.githubusercontent.com/5630104/102932372-12704f00-4498-11eb-8bd7-1c41795a0f4a.png)

**Comment by MadLad1Clip** [comment]
The fix for property inventroy was 
![image](https://user-images.githubusercontent.com/5630104/102993268-bef01680-4514-11eb-9c45-cfde8bba5a7e.png)
