### ISSUE TITLE
Property Inventory Broken.

### ISSUE THREAD

**Issue by MadLad1Clip** [dutchplayers/FiveM-Resources#242]
Still a problem with the property inventory, The inventory opens but is unuseable throwing this error in console.
![image](https://user-images.githubusercontent.com/5630104/103154622-82c8ea00-4790-11eb-81a0-cde46ce1da67.png)

**Comment by AgenChicken24** [comment]
can you show line 363 in the esx_property and for the money the problem was in the property in my server. This is the code that was missing  
![image](https://user-images.githubusercontent.com/64702468/103155260-a139e000-47a6-11eb-9e2c-a6f5304c9c37.png)

**Comment by MadLad1Clip** [comment]
Looking into the problem there might be something else at play with this ill update when I can.
