### ISSUE TITLE
Ammo bug

### ISSUE THREAD

**Issue by GyurkaSanel** [dutchplayers/FiveM-Resources#244]
Dear,
I have a problem with ammunition database.When I buy ammo and I load it in a weapon it raise the count INT in the database as it have to do. But here comes the problem. When i start shooting and reload the clip it not subtract the shooted ammos from database and leave as it was.
![image](https://user-images.githubusercontent.com/76791083/103377241-21ca4a80-4adf-11eb-8554-0020b4bea42a.png)

For example i have 45 ammos in the weapon and when i start shooting the ammunition number won't reduce.
Any solutions?

**Comment by Jabelius** [comment]
It updates the database when weapon is removed from hands afaik.
