### ISSUE TITLE
Bag bug

### ISSUE THREAD

**Issue by SteveBaggins** [dutchplayers/FiveM-Resources#248]
**Describe the bug**
I have seen a few issues relating to bags. It appears to create a full table of every item in the db per player who uses one. But the real issue we have seen is that sometimes after using the bag, players can't open it at all. Sometimes a restart fixes it, but it throws a xplayer nil value error in console anytime this happens. I checked the line of code, its just a generic check playerdata line and should not really cause issues but a relog seems to fix it 50/50

Not really sure how to reproduce it as it randomly happens to some and not others.

**Comment by Luxoruus** [comment]
Remove line number 5 in client/bag.lua:
`PlayerData = xPlayer`
