### ISSUE TITLE
WeaponShop no License

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#249]
Hello, I can't use the WeaponShop it won't let me buy a license my money is decreasing, but I'm not getting any license to access the WeaponShop

**Comment by Heavens-c** [comment]
do you have the weapon license in database

**Comment by ghost** [comment]
> do you have the weapon license in database

I got one in "licenses" called "weapon" is it right ?

**Comment by Borea** [comment]
Check if the user has the licence

**Comment by Borea** [comment]
#253 check my solution

**Comment by Heavens-c** [comment]
solve..

**Comment by ghost** [comment]
> #253 check my solution

Thanks it's working
