### ISSUE TITLE
Trunk and Glovebox still broken

### ISSUE THREAD

**Issue by steveski** [dutchplayers/FiveM-Resources#254]
So I've had this sql duplicate error popping up on our server due and found this resolution "[Not tested, but this should fix it](https://github.com/dutchplayers/FiveM-Resources/commit/26246d576d72eb8d2ecb1b59131225986901e94e)".

It's the wrong solution! You have avoided the duplicationg error showing but it's just a bandage full of pus that needs to be properly fixed. All you actually needed was to get SharedDataSources populating on launch, it's always nil ... I put print statements in the onMySQLReady event handler and they weren't being printed.
I fixed this duplicate error only by changing this:
```
--AddEventHandler("onMySQLReady", function()
MySQL.ready(function()
```
Which means that the decision to NOT do an insert determined here will actually work correctly now:

```
function GetSharedDataStoreTrunk(plate)
	if SharedDataStores[plate] == nil then
		MakeDataStoreTrunk(plate)
	end
	return SharedDataStores[plate]
end
```

Of note though is that this error woudn't have any adverse effects in game, the SharedDataStores[plate] call returns nil but will create the entry in memory as well as fail an INSERT but the next time around the call to SharedDataStores[plate] returns a value. It's just tedious to see errors that don't need to be there.

Another point to note is that NOW the owned = 0 entries from trunk and glovebox inventories tables actually removed on startup. I saw this code and initially was confused about why I still had entries with owned = 0.
I actually think it's a bad idea to delete this anyway because if there's a server crash and restart, anyone with job inventory loses any possibility of ever being able to prove to server admins that they had the inventory. What I intend to do is create a job_vehicle table and when you spawn a job vehicle it will put the license plate and player ID there and when the player returns the vehicle the entry gets deleted. The DELETE statement would then be udpated to only delete if on a LEFT JOIN to that job_vehicle table the identifier = NULL. Still need to think about how to handle deletion if they merely never return the vehicle though.

At any rate, I firmly believe the people contributing code here don't test anything. I know I'm coming across harsh, but I've had to do a monolithic amout of work to get this resource running. Was deeply annoyed to find no one notice the on MySQL ready cleanup step doesn't run. Even the most obvious flaws are going unnoticed

**Comment by Magnemice** [comment]
What do you change?

**Comment by steveski** [comment]
It's in my message above.
```
--AddEventHandler("onMySQLReady", function()
MySQL.ready(function()
```

**Comment by Magnemice** [comment]
in wich code client lua?

**Comment by RuisSoftware** [comment]
thanks
