### ISSUE TITLE
lockers issue

### ISSUE THREAD

**Issue by bashon1** [dutchplayers/FiveM-Resources#256]
Hello

the problem is happen when i try add cash or blackmoney in to lockers
https://prnt.sc/xbqw8i

**Comment by mahmoudadel14** [comment]
add this in addon_account sql
![10](https://user-images.githubusercontent.com/54334373/106311098-4005a080-626d-11eb-8e38-84653d9e8a96.png)

locker_cash
locker_black

**Comment by bashon1** [comment]
i already have it

**Comment by RuisSoftware** [comment]
Last updates fixes this
