### ISSUE TITLE
Can't give and drop money issue

### ISSUE THREAD

**Issue by Evilcho0TM** [dutchplayers/FiveM-Resources#257]
This is the error when i try to give money or drop ?
SCRIPT ERROR: @es_extended/server/main.lua:387: attempt to index a nil value (local 'account')

![Screenshot_1](https://user-images.githubusercontent.com/64500013/105646641-9c517480-5ea9-11eb-86c9-672ed17fed1d.png)

**Comment by Evilcho0TM** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/64500013/105646654-b5f2bc00-5ea9-11eb-84a2-aa69ca28d665.png)

**Comment by Tomlec7** [comment]
I got the same issue
