### ISSUE TITLE
Weapon apears when you get of a motorbike

### ISSUE THREAD

**Issue by pablo-rico** [dutchplayers/FiveM-Resources#258]
**Describe the bug**
Without having any weapons in the inventory, the script grants a pistol to the user when getting off a vehicle, usually motorcycles

**To Reproduce**
1. Have all instaled (ESX 1.2FINAL, all SQL OK)
2. Mount a motorcycles and try to shoot, after that there is a chance that the bug apears

**Expected behavior**
Without having weapons, no weapon should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/22524425/106394979-f6998a80-63ff-11eb-9c94-71e026e4c523.png)

**ESX version:**
 - Version 1.2  FINAL

**Followed Wiki**
Yes

https://www.dutch-players.nl/joindiscord

**Comment by bashon1** [comment]
some issue for all version this inventory

**Comment by ZypsohDEV** [comment]
thats not a issue thats a normal thing in gta v, create a resource to stop giving that weapons , its simple

**Comment by ZypsohDEV** [comment]
also it justs happens in police motorcycles
