### ISSUE TITLE
Some problems (Invisible weapon after charge, shops)

### ISSUE THREAD

**Issue by LuigiiMcQueen** [dutchplayers/FiveM-Resources#260]
Hi guys, anyone can help me with DP_Inventory?  I have some problemas and i can't fix it already. Thanks!
I am not able to access the inventory of all companies (police, inem, gangs, etc.) It gives error "attempt to index a nil value (local 'inventory'), the other problem I am having is when I reload the weapons it leaves the hand and I have to press the key 2 to take it out because it is invisible and put it back on, do you know how to solve it? And you still know why some of the stores can't be opened? Ammunation for example can't and the Supermarket too no, besides all the stores work. Excellent script, congratulations and thanks in advance!

**Comment by Dallepower** [comment]
I'm currently having the same issue with the guns. Did you fix it?
