### ISSUE TITLE
Stuck With fuel can in my hand

### ISSUE THREAD

**Issue by Zach488** [dutchplayers/FiveM-Resources#261]
**Describe the bug**
When i buy a  fuel can at the gas station with legacy fuel i get the fuel can stuck to me and dont see it in my inventory

**ESX version:**
 - Version 1.2

**Comment by detrax112** [comment]
I have the same problem too unfortunately. Someone solved that bug?  Because my only solution was to disable the JerryCan from LegacyFuel..
