### ISSUE TITLE
How to make Cash appear with $ instead of Euros?

### ISSUE THREAD

**Issue by Duguayster** [dutchplayers/FiveM-Resources#263]
Simple question for someone who might know...

I'd like to change out the € sign for the $ sign? How can I do that?

Thanks!

**Comment by Luxoruus** [comment]
Hi, change this
https://github.com/dutchplayers/FiveM-Resources/blob/09c49f751fd2deeb4f2063df73189f4ab57b46fd/ESX/Inventory%20HUD/DP_Inventory/html/js/inventory.js#L404-L406
by this
```js
function formatMoney(number) {
	return number.toLocaleString('nl-NL', { style: 'currency', currency: 'USD' });
}
```
and here's a link for other currencies: https://www.currency-iso.org/dam/downloads/lists/list_one.xml

**Comment by Duguayster** [comment]
Thank you so much for your reply! <3
