### ISSUE TITLE
Storage inventory items 'Undefined' with vault resources

### ISSUE THREAD

**Issue by Haidee-hm** [dutchplayers/FiveM-Resources#268]
**Describe the bug**
Items that are placed into the vault (using the built in MonsterVault code) show their name as undefined.  The only exception to this is cash which I have manually added into the en.lua file.

**To Reproduce**
1. Placed an item in the vault
2. Item name is updated as 'undefined'

**Expected behavior**
I would like the items to use their label name just like the shops do.

**Screenshots**
![VaultInventory](https://user-images.githubusercontent.com/44797604/110594424-a91ff280-81e1-11eb-8d86-6c5b0c75a76b.PNG)

**ESX version:**
 - 1.2

**Additional context**
n/a

**Followed Wiki**
Yes

**Comment by eltison** [comment]
The items are marked indefinitely while the database records the names. The next time the server reboots, the names will appear

**Comment by Haidee-hm** [comment]
Hi eltison,

I can confirm that the items still remain named 'undefined' after multiple server restarts.

**Comment by RuisSoftware** [comment]
We are unable to reproduce this error. If you can send us any error code or more details about how to reproduce, we're glad to hear from you.
