### ISSUE TITLE
Inventory make some other menus like esx_specate not work with hotkey and just work with command!

### ISSUE THREAD

**Issue by YInfeRnal** [dutchplayers/FiveM-Resources#269]
hi the inventory make other menus not work and not open!
for examble my esx_spectate on j but when i press j buttom anything not happen and the menu not run but when i use /specate the menu is appear! why this happen? when inventory is turn on everything fine but when is turn off anything fucked up...
please help Me.

**Comment by RuisSoftware** [comment]
Wierd, our inventory is only registering a key specified in the config, nothing more.

There are no natives that could change other keys
