### ISSUE TITLE
MF PlayerSafe Support

### ISSUE THREAD

**Issue by bdebruyn02** [dutchplayers/FiveM-Resources#271]
Player Safe Support for MF Player Safes

**Comment by CassO170** [comment]
I'm having a lot of problems getting MF_PlayerSafes to work on our development server so I'm unable to implement it in our city.  Accessing the inventory or the safes works once... on the second attempt to access the client crashes with no errors on console.  The readme that shipped with the script makes reference to a discord webhook but there was no server at the provided link.
