### ISSUE TITLE
Error parsing script @DP_Inventory/server/vault.lua in resource DP_Inventory: @DP_Inventory/server/vault.lua:235: unexpected symbol near 'then'

### ISSUE THREAD

**Issue by bdebruyn02** [dutchplayers/FiveM-Resources#272]
![image](https://user-images.githubusercontent.com/31498965/111269913-dcc2a880-8637-11eb-814e-1bb19a25e42a.png)

FIX:
if item.job == 'police' or item.job == 'nightclub' then
			TriggerEvent('esx_addonaccount:getSharedAccount', typeVault..'_money', function(account)
				money = account.money
			end)

**Comment by RuisSoftware** [comment]
Yes thanks!
