### ISSUE TITLE
Inventory UI is different from the Picture

### ISSUE THREAD

**Issue by rhoy1871** [dutchplayers/FiveM-Resources#280]
Hi,

I download the latest one, But the UI is different from what's in the pictures below
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3533383833343139363435383839373430382f3737393935323932373337363533393732382f44505f496e76656e746f72792e6a7067](https://user-images.githubusercontent.com/40468854/113650313-016dd700-965e-11eb-8c2e-9a8b8b7eaf0d.jpeg)

Inventory Ver 1.3

ESX1.2 final

**Comment by RuisSoftware** [comment]
True, thats the old design

**Comment by rhoy1871** [comment]
Ow ok. Thank you
