### ISSUE TITLE
Mythic_Progbar "exports function" not removed.

### ISSUE THREAD

**Issue by zcore-framework** [dutchplayers/FiveM-Resources#281]
Incorrect bug report.

Please disregard.

**Comment by RuisSoftware** [comment]
what?

**Comment by zcore-framework** [comment]
> what?

The Mythic_Progbar resource is still being called as an exports function, even though support for it is no longer available given your recent commits. Should it not be updated as well with t-notify?

**Comment by RuisSoftware** [comment]
Ah i see.

T-notify is only a replacement for mythic-notify and b1g-notify

**Comment by zcore-framework** [comment]
Great. Thanks!
