### ISSUE TITLE
CREATE TABLE IF NOT EXISTS `ammunition

### ISSUE THREAD

**Issue by bmwso96** [dutchplayers/FiveM-Resources#284]
When i try to import the sql file i get an error while creating this table.

error : SQL Error (1101): BLOB/TEXT column 'attach' can't have a default value */

this is the code im trying to run 

CREATE TABLE IF NOT EXISTS `ammunition` (
    `id` bigint unsigned auto_increment PRIMARY KEY,
    `owner` text,
	`original_owner` text not null,
    `hash` text not null,
	`weapon_id` char(60) NOT NULL,
    `count` int default 0 not null,
    `attach` text not null default '[]',
	UNIQUE KEY (`weapon_id`)
);
**copied from sql file**
any idea how to fix ?

**Comment by theFOX1337** [comment]
replace
`attach text not null default '[]',`
with
`attach text not null,`
