### ISSUE TITLE
DP_Jobs_Menu

### ISSUE THREAD

**Issue by Maxamax1** [dutchplayers/FiveM-Resources#288]
**Describe the bug**

When i load the ressource i get a Error in F8 Console and the Menu is miss aligned

**To Reproduce**
1. load the ressource DP_Jobs_Menu
2. Open F8
3. Look at the Error

**Expected behavior**

No Error?

**Screenshots**
![image](https://user-images.githubusercontent.com/74760408/116397497-efc7bb80-a826-11eb-9f0b-07c9d0f1259b.png)
![image](https://user-images.githubusercontent.com/74760408/116397539-fe15d780-a826-11eb-9b32-45dbcbf2f584.png)

**ESX version:**
 - Version [Final V1]

**Additional context**
Uncaught TypeError: Cannot read property 'style' of null (@dp_jobs_menu/html/js/index.js:168)
**Followed Wiki**
Yes

https://www.dutch-players.nl/joindiscord

**Comment by RuisSoftware** [comment]
Thanks, will look into this

**Comment by RuisSoftware** [comment]
Deprecated
