### ISSUE TITLE
Might not be an actual issue

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#29]
Like the title says, I do not know if this is an actual issue but looking throught the main.lua in the server folder for esx_inventoryhud, I came across this multiple times.

`TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'error', text = 'You do not have enough space in your inventory!' })`

**'mythic_notify:client:SendAlert'** instead of **'b1g_notify:client:Notify'**

I haven't tried changing it since I didn't want to possibly break the plugin.

**Comment by RuisSoftware** [comment]
Hi and thank you! Indeed i missed some. I will update this soon
