### ISSUE TITLE
just use esx 1.2 version

### ISSUE THREAD

**Issue by BattleStar247** [dutchplayers/FiveM-Resources#290]
just use esx 1.2 version

_Originally posted by @dutchplayers in https://github.com/dutchplayers/FiveM-Resources/issues/7#issuecomment-830644101_

**Comment by BattleStar247** [comment]
i am on v1final still got this issue

**Comment by RuisSoftware** [comment]
If you use ESX 1.2 then you should be using: https://github.com/dutchplayers/FiveM-Resources/tree/master/ESX/Inventory%20HUD/ESX%20v1.2%20(v1-final)/DP_Inventory
