### ISSUE TITLE
No sound with the dutch radio

### ISSUE THREAD

**Issue by GhostgamesDHG** [dutchplayers/FiveM-Resources#291]
I have the dutch radio installed into my server, but the sound doesn't work. The icons do work. I live in the netherlands.

**Comment by GhostgamesDHG** [comment]
I have fixed it. the fxmanifest was not good. I can do a pull request.

**Comment by RuisSoftware** [comment]
Thanks :)

**Comment by GhostgamesDHG** [comment]
no problem.
