### ISSUE TITLE
Trunk of Trucks

### ISSUE THREAD

**Issue by Anon0p** [dutchplayers/FiveM-Resources#296]
Trunk of Trucks not working after new update. Any fix ?

**Comment by LeoLight868** [comment]
same issue here, cant open trunk for Trucks with trailers.

**Comment by Maxamax1** [comment]
same issue

**Comment by Maxamax1** [comment]
i know its not pretty but its a solution you have to add the truck names to the vehicleTable trunk.lua:15 as a Example: ['pounder']=3
https://github.com/Maxamax1/FiveM-Resources/blob/master/ESX/Inventory%20HUD/ESX%20v1.2%20(v1-final)/DP_Inventory/client/trunk.lua

**Comment by iSentrie** [comment]
trailers should have trunk too
![image](https://user-images.githubusercontent.com/29688478/118393986-a4951180-b64a-11eb-8dfd-be8007366720.png)
