### ISSUE TITLE
Ammo doesn't gets saved after firing

### ISSUE THREAD

**Issue by sFxMTA** [dutchplayers/FiveM-Resources#297]
**Description**
If you get 10 ammo (as example) and you fire when you reconnect you still got 100 ammo

**To Reproduce**
1. I used /giveitem ID WEAPON_PISTOL 1
2. I took a clip and put it in there
3. I got X amount of ammo and i started to fire some of them, so i got Y ammo left in the weapon
4. I made /disconnect and once i got back i got X ammo instead of Y

**Expected behavior**
Saving the ammo once the player disconnects in order to get the left ammo instead of the ammo you've set at the start

**Video**
https://streamable.com/84vq32

**ESX version:**
 - ESX1 Legacy (Latest version, updated less than a week ago)

**Followed Wiki**
Yes

https://www.dutch-players.nl/joindiscord

**Comment by Skillgjii** [comment]
same problem on my server
