### ISSUE TITLE
FiveM inventory Bug

### ISSUE THREAD

**Issue by MrMazzie** [dutchplayers/FiveM-Resources#302]
**Describe the bug**
so basically i bought a script for my FiveM server. 
inventory HUD 5 
https://shoppy.gg/product/HD5McK0
and i added it on my server and for some reason if i buy something at a shop and use the item that i bought , the item does not deduct / go out of inventory 

i have all the sql files imported to my php admin .
does anyone know a fix or something ?
![inventory bug](https://user-images.githubusercontent.com/84808853/119556707-9c9e4580-bd9f-11eb-99b7-68db4ddffd70.png)
![console error](https://user-images.githubusercontent.com/84808853/119556798-bb044100-bd9f-11eb-8685-b1b95560ee30.png)

**Comment by Pride1922** [comment]
Ask support from whomever you bought the script? 
It seems to me pretty unfair that you bought a script and then go ask support to those who are working for free?

You could ditch that inventory, start using the free dp_inventory and donate whatever you want for their script. So they can keep this alive.
