### ISSUE TITLE
[BUG] Using Weapon (Hotbar)

### ISSUE THREAD

**Issue by detrax112** [dutchplayers/FiveM-Resources#305]
Describe the bug:
I added some weapons to the WeaponShop and i leaved the ammos in the WeaponShop too. The problem is when i try to use the weapon. It make the animation but the weapon not showing up (All the weapons) . Somtimes it showing up for 2-3 seconds but when i try to use it , it dissapear.

ESX version:
 - Version 1.2 (v1final)

**Comment by OffTheRipRP** [comment]
Hey, did you figure this out?

**Comment by RuisSoftware** [comment]
Alright. 

Do not use /giveweapon
Use /giveitem instead.

Example: /giveitem 1 WEAPON_PISTOL 1
Be sure to use the correct item name, you can find this in your database.
