### ISSUE TITLE
Issue with hotbar shortcut

### ISSUE THREAD

**Issue by roobr** [dutchplayers/FiveM-Resources#306]
**Describe the bug**
When opening inventory the hotbar displays the items in the hotbar but not in the "Shortcut" Section

**To Reproduce**
1. click tab to open inventory and right click to assign something
2. open inventory again and there is no items in the "Shortcut" but still function correctly in your hotbar with 1-5 keybinds
 

**Expected behavior**
Items should display correctly in the "Shortcut" section of the inventory hud at all times when there is an item value stored in that slot

**Screenshots**
![image](https://user-images.githubusercontent.com/9066749/121137737-51456600-c87a-11eb-9ded-45320b4f50ac.png)

**ESX version:**
 - Version final

https://www.dutch-players.nl/joindiscord

**Comment by Dallepower** [comment]
+1
