### ISSUE TITLE
Cant Keep Weapons on trunk and glovebox. I

### ISSUE THREAD

**Issue by SpectrumRaijin** [dutchplayers/FiveM-Resources#307]
When I open the trunk inventory or glovebox I cant keep the weapons.  Only normal items and money.

The other problem I Have, I use Core_weapon script for weapon accesories. when I try to use, it makes an animation and keep my weapon If i use other inventory I can use the item without any problem the accesory attach to the weapon without any problem

**Comment by SpectrumRaijin** [comment]
![image](https://user-images.githubusercontent.com/83751111/121412193-0c790800-c92a-11eb-98b0-d7a99c5cb270.png)

**Comment by SpectrumRaijin** [comment]
My mistake. Now all weapon works with item. So i understand the system.  Your Inventory is perfect

**Comment by Arcticguy867** [comment]
> ![image](https://user-images.githubusercontent.com/83751111/121412193-0c790800-c92a-11eb-98b0-d7a99c5cb270.png)

What inventory is that ??
