### ISSUE TITLE
fixed the brinksjob sql file

### ISSUE THREAD

**Issue by leonard11255** [dutchplayers/FiveM-Resources#309]
im not used to upload fixes to github and I think I did it the right way like this? anyway here is is: 

INSERT INTO `jobs` (`name`, `label`) VALUES
('brinks', 'Brinks');

INSERT INTO `job_grades` (`job_name`, `grade`, `name`, `label`, `salary`, `skin_male`, `skin_female`) VALUES
('brinks', 0, 'employee', 'Medewerker', 200, '{"tshirt_1":44,"torso_1":98,"arms":14,"pants_1":47,"glasses_1":0,"decals_2":0,"hair_color_2":0,"shoes_1":25,"helmet_2":2,"b_proof_1":4,"bproof_2":0,"shoes_2":0,"bproof_1":0,"hair_color_1":0,"face":2,"glasses_2":0,"torso_2":1,"shoes":25,"hair_1":0,"skin":0,"sex":0,"glasses_1":0,"pants_2":1,"hair_2":0,"bproof_2":0,"decals_1":0,"tshirt_2":0,"helmet_1":10}','{"tshirt_1":44,"torso_1":98,"arms":14,"pants_1":47,"glasses_1":0,"decals_2":0,"hair_color_2":0,"shoes_1":25,"helmet_2":2,"b_proof_1":4,"bproof_2":0,"shoes_2":0,"bproof_1":0,"hair_color_1":0,"face":2,"glasses_2":0,"torso_2":1,"shoes":25,"hair_1":0,"skin":0,"sex":0,"glasses_1":0,"pants_2":1,"hair_2":0,"bproof_2":0,"decals_1":0,"tshirt_2":0,"helmet_1":10}');

**Comment by RuisSoftware** [comment]
Thanks!
