### ISSUE TITLE
MYSQL issue

### ISSUE THREAD

**Issue by frazz1234** [dutchplayers/FiveM-Resources#318]
I instal the mysql you told to for this inventory and now esx is fuck! THe DP still not opening and now my charactere not loading! thanks 

[  script:es_extended] SCRIPT ERROR: @mysql-async/lib/MySQL.lua:145: The SQL Query must be a string
[  script:es_extended] > fetchAll (@mysql-async/lib/MySQL.lua:145)
[  script:es_extended] > ? (@es_extended/server/main.lua:133)
[  script:es_extended] > fn (@async/async.lua:18)
[ script:DP_Inventory] SCRIPT ERROR: @DP_Inventory/server/main.lua:81: attempt to index a nil value (local 'xPlayer')
[ script:DP_Inventory] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[ script:DP_Inventory] > handler (@es_extended/server/common.lua:83)
[  script:es_extended] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:765: bad argument #1 to 'table_unpack' (table expected, got nil)
[  script:es_extended] (nil stack trace)

**Comment by RuisSoftware** [comment]
That's not intended. I'm updating the repo currently
