### ISSUE TITLE
Suggestion / Enchancement

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#39]
I got this idea from a resource I am currently using that offers something similar.

I noticed that in your recent updates, you've added shops, weaponshops, etc, into your plugin which I think is actually amazing but I would like to disable the YouTool and Prison Shop but in the config file there is no way of doing it without probably breaking the plugin so my suggestion is that you somehow find a way that players can easily activate/deactivate the fuctions they wish.

This is just an example;

Config.Extras = { -- True means that they want the option
        RegularShop = true, 
	RobsLiquor = true,
        YouTool = true,
        PrisonShop = true,
        WeaponShop = true,
        LicenseShop = true,
}

Also, I would suggest changing the key for opening the glovebox/trunk to something else than **F3** since it is the default key for [esx_animations](https://github.com/ESX-Org/esx_animations) and [dpEmotes](https://github.com/andristum/dpemotes). Maybe something like **L**, i've seen it in multiple server for opening the trunk.

**Comment by FiveEYZ** [comment]
simplest way to disable a shop would be to comment away the coords
```lua
    PrisonShop = {
        Locations = {
            --{x = 1728.41, y = 2584.31, z = 45.84},
        },
        Items = {
            {name = 'bread'},
            {name = 'water'}
        }
    },
```

for the keybind u can find a config file inside both `esx_inventoryhud_glovebox` and `esx_inventoryhud_trunk` where you can change `Config.OpenKey`

**Comment by ghost** [comment]
I didn't think that would work :(

Thank you for you're fast reply.
