### ISSUE TITLE
error esx_trunk-sv.lua:138

### ISSUE THREAD

**Issue by tonibanks** [dutchplayers/FiveM-Resources#4]
SCRIPT ERROR: @esx_inventoryhud_trunk/server/esx_trunk-sv.lua:138: attempt to compare number with nil

**Comment by HstufAmir** [comment]
i have same problem...this error fk my mind.
i cant fix it.
TakeFromTrunk and esx_trunk:getitem not return the item`s limit


please help me 
tnx

**Comment by TMarcccci** [comment]
Same problem please help

**Comment by HstufAmir** [comment]
bro i fix it but have a bug

**Comment by TMarcccci** [comment]
Whats your discord name? HstufAmir

**Comment by HstufAmir** [comment]
Hstuf.Amir #4165

**Comment by BennoArnautovic** [comment]
Same issue, anyone have solution for this ? 
Issue is reproducible also for glovebox ? 

Please help, thanks!

**Comment by jimmydesilva** [comment]
This thread will probably solve all your issues:

https://forum.cfx.re/t/how-to-fix-solved-attempt-to-index-a-nil-value-local-xplayer-server-crash/100135/1

**Comment by RuisSoftware** [comment]
Please try the update
