### ISSUE TITLE
Inventoryhud shops

### ISSUE THREAD

**Issue by fredwoot** [dutchplayers/FiveM-Resources#43]
I have an error while using the shop. Everything else works fine except for this so I cant buy anything. The DB is correctly built with prices, I did disabled the default esx inventory and modified esx_addoninventory.

![Capture](https://user-images.githubusercontent.com/41339839/80290542-ab857500-8713-11ea-98f0-3128b549b805.PNG)
Hope someone can help me with this because that's the only thing holding me from using it.
Thank you

**Comment by haarperr** [comment]
are u use old version of extended?

**Comment by fredwoot** [comment]
Well not the latest because the original author of es_extended has been shot down on github (dmca) and I use a modified version from last december to use the double job...

**Comment by fredwoot** [comment]
I did find a up to date version of es_extended and still the same error... ?

![Capture](https://user-images.githubusercontent.com/41339839/80292746-c0b7cf00-8726-11ea-8c67-d4c12544df5d.PNG)

**Comment by fredwoot** [comment]
The error actually happens when I drag the item from the shops inventory to my personal inventory. The 3 errors are the 3 drags attempt.

**Comment by FiveEYZ** [comment]
https://github.com/KandaSoranyan/es_extended can be used til official repo is available again

**Comment by fredwoot** [comment]
Thank you
I did found the problem at server/main.lua 344

Original one:
if xPlayer.canCarryItem(item, count) then
        --if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then

The line uncomment/comment must be replace like this:
        --if xPlayer.canCarryItem(item, count) then
  if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then
