### ISSUE TITLE
es_extended problem

### ISSUE THREAD

**Issue by ghost** [dutchplayers/FiveM-Resources#44]
Tried doing that;

Open es_extended, then find and remove this code in `client/main.lua`:
```
-- Menu interactions
Citizen.CreateThread(function()
	while true do

		Citizen.Wait(0)

		if IsControlJustReleased(0, Keys['F2']) and IsInputDisabled(0) and not isDead and not ESX.UI.Menu.IsOpen('default', 'es_extended', 'inventory') then
			ESX.ShowInventory()
		end

	end
end)
```
but I can't find it in the file. I think they changed the code.

Here is my `client/main.lua` file. --> https://pastebin.com/5RdNJzBw

**Comment by RuisSoftware** [comment]
If you can't open the default inventory then it's fine.
