### ISSUE TITLE
Missing license and credits of original resource

### ISSUE THREAD

**Issue by Trsak** [dutchplayers/FiveM-Resources#45]
Hello,
your code comes from original esx_inventoryhud that was released under GNU GPL v3 license.

You have to use the same license and keep credits of the original resource:
`Original esx_inventoryhud resource made by Trsak.`

Please take your time to do this or i will be forced to make DMCA report and your code will be taken down. 
Thanks.

**Comment by xrtw** [comment]
lmao

**Comment by RuisSoftware** [comment]
Thank you for letting me know. Also thank you for the original work! We all love this a lot.

**Comment by RuisSoftware** [comment]
Hi, i've made some changes please review them. If you have any objections i'm here for you!
