### ISSUE TITLE
police searching gives an error

### ISSUE THREAD

**Issue by oogienl** [dutchplayers/FiveM-Resources#50]
hey, im having problems whenever police is searching someone they can see the items but they can not take them, console gives the following error while trying to drag and im using the latest es_extended https://gyazo.com/b4ce1a7f7f62c81cb7e37793bbd8e6f0. i hope somebody could help me out as this is an important game mechanic that should work :)

**Comment by oogienl** [comment]
fixed

**Comment by iiAlphaWolf** [comment]
Yo how did you solve this m8?
