### ISSUE TITLE
New fonction

### ISSUE THREAD

**Issue by Enric42** [dutchplayers/FiveM-Resources#51]
hi , I think it would be quite simple and very cool to be able to add this
 https://github.com/MonsterTaerAttO/monster_vault

to your addon in addition to glovebox, bed, trunk ....

it would be really cool to have vault that we can generate with coordinates and for each to assign an item or not to open it

what do you think ?

**Comment by RuisSoftware** [comment]
Thanks! Just added it!

**Comment by Enric42** [comment]
Thx , is possible to modify vault system for he work not with a job , but with only item


like this the users can place for example in the config a vault1, vault 2 vault 3 ... etc in different places
and each is public but requires an item to be opened this is much better allows more possibility and realism

**Comment by RuisSoftware** [comment]
You can contact us at our Discord server for more support @Enric42
