### ISSUE TITLE
double weapon

### ISSUE THREAD

**Issue by xrtw** [dutchplayers/FiveM-Resources#52]
to do that, you need a friend. stay near the trunk. open trunk, then give your weapon to your friend (but don't click on your friend nickname in give menu), move weapon to the trunk and after that just press your friend nick in the Give button.

**Comment by RuisSoftware** [comment]
Thank you will look into it

**Comment by maguhd** [comment]
Have you guys looked into this? Is it still possible?

**Comment by Tinky124** [comment]
its still issue

**Comment by RuisSoftware** [comment]
Should be fixed now.
