### ISSUE TITLE
notify don't work

### ISSUE THREAD

**Issue by ricepunk** [dutchplayers/FiveM-Resources#56]
notify does not appear in player
For example: when the police are searching and retrieving items

https://github.com/dutchplayers/esx-inventoryhud/blob/0db1a279cca533ef55984b273bc1aee97247d629/esx_inventoryhud/server/main.lua#L41

https://github.com/dutchplayers/esx-inventoryhud/blob/0db1a279cca533ef55984b273bc1aee97247d629/esx_inventoryhud/server/main.lua#L43

**Comment by RuisSoftware** [comment]
Will test that if when im online

**Comment by RuisSoftware** [comment]
I will soon change the used notify system from B1G to mythic.
