### ISSUE TITLE
inventory doesn't open

### ISSUE THREAD

**Issue by TUFLipton** [dutchplayers/FiveM-Resources#58]
when i press F2, inventory doesn't open, i don't have the ability to open any shops, however, when i press F3 behind the car it says the trunk is closed, and when i press F3 in vehicles, the car slightly jumps.  so i'm assuming i have the mod working, i just can't get the UI to open?

**Comment by RuisSoftware** [comment]
Any errors?

**Comment by RuisSoftware** [comment]
If you need further support please visit our Discord server.
