### ISSUE TITLE
Controller Keybind conflict

### ISSUE THREAD

**Issue by blk07shelbygt** [dutchplayers/FiveM-Resources#6]
Controller users are complaining when they hit Y on their Xbox controller it opens inventory. I want to keep it on F2 but don't see where I can change the coding to only work on a keyboard

**Comment by RuisSoftware** [comment]
Please send a pull request to improve this :)

**Comment by for** [comment]
I use this for that exact reason in - \client\main.lua
`Citizen.CreateThread(
    function()
        while true do
            Citizen.Wait(0)
            if IsControlJustReleased(0, Config.OpenControl) and IsInputDisabled(0) then
                openInventory()
            end
        end
    end
)`

**Comment by RuisSoftware** [comment]
Download 1.4 when its released
