### ISSUE TITLE
Motel Inventory still not working

### ISSUE THREAD

**Issue by Rado236** [dutchplayers/FiveM-Resources#64]
**Describe the bug**
When I went to my motel room and tried using the inventory. it poped up but I couldnt store anything in it. I am using LSRP_Motels

**To Reproduce**

**Expected behavior**
To store my items

**Screenshots**

**ESX version:**
 - Version [e.g. 1.2]
1.2

**Additional context**

**Followed Wiki**
Yes

**Comment by FB-Syntax** [comment]
Works to me... do you follow lsrp_motels instruction? you need to remove some lines and add some lsrpmotel code.

**Comment by squieler** [comment]
Add this two line to esx_inventoryhud/fxmanifest.lua

`exports{
  "refreshPropertyMotelBedInventory",
  "refreshPropertyMotelInventory"
}`

**Comment by ghost** [comment]
Make sure you have Mythic Progressbar ('mythic_progbar') and add these lines at the bottom of esx_inventoryhud/fxmanifest.lua and try again:

> exports{
  "refreshPropertyMotelBedInventory",
  "refreshPropertyMotelInventory"
}

**Comment by Rado236** [comment]
Added the exports in the fxmanifest file still the same bug. Checked out inventory.js file and the code lines seem to be correctly added.

**Comment by RuisSoftware** [comment]
> 
> 
> Make sure you have Mythic Progressbar ('mythic_progbar') and add these lines at the bottom of esx_inventoryhud/fxmanifest.lua and try again:
> 
> > exports{
> > "refreshPropertyMotelBedInventory",
> > "refreshPropertyMotelInventory"
> > }

What does this actually do? I can add this to original code

**Comment by Rado236** [comment]
Well I got some progress I managed somehow to get the motel beds at half working, what I mean- I can store items inside but cannot withdraw them.

**Comment by FB-Syntax** [comment]
> Well I got some progress I managed somehow to get the motel beds at half working, what I mean- I can store items inside but cannot withdraw them.

you need to add some lines in inventory.js to work all function.

**Comment by RuisSoftware** [comment]
> 
> 
> > Well I got some progress I managed somehow to get the motel beds at half working, what I mean- I can store items inside but cannot withdraw them.
> 
> you need to add some lines in inventory.js to work all function.


Can you send it in a pull request?

**Comment by ghost** [comment]
> > Make sure you have Mythic Progressbar ('mythic_progbar') and add these lines at the bottom of esx_inventoryhud/fxmanifest.lua and try again:
> > > exports{
> > > "refreshPropertyMotelBedInventory",
> > > "refreshPropertyMotelInventory"
> > > }
> 
> What does this actually do? I can add this to original code

I double checked now, there is no need for exporting any functions, my mistake but FB-Syntax right.

**Comment by Rado236** [comment]
> > > Well I got some progress I managed somehow to get the motel beds at half working, what I mean- I can store items inside but cannot withdraw them.
> > 
> > 
> > you need to add some lines in inventory.js to work all function.
> 
> Can you send it in a pull request?

if i get all functions fixed then probably will

**Comment by RuisSoftware** [comment]
> 
> 
> > Well I got some progress I managed somehow to get the motel beds at half working, what I mean- I can store items inside but cannot withdraw them.
> 
> you need to add some lines in inventory.js to work all function.

Thanks
