### ISSUE TITLE
Turkish language p.rq

### ISSUE THREAD

**Issue by vayazi** [dutchplayers/FiveM-Resources#65]
Locales["tr"] = {
	["cash"] = "Para",
	["black_money"] = "Kara Para",
	["player_nearby"] = "Oyuncu artık yakında değil!",
	["players_nearby"] = "Etrafında başka oyuncu yok!",
	["openinv_help"] = "Diğer oyuncunun envanterini açın.",
	["openinv_id"] = "Oyuncu IDsi",
	["no_permissions"] = "Bunu yapmaya yetkin yok!",
	["no_player"] = "Oyuncu bulunamadı!",
	["player_inventory"] = "Oyuncu envanteri",
	["nacho_veh"] = "Bu senin araban değil.",
	["player_inv_no_space"] = "Envanter alanı yok.",
	["insufficient_space"] = "Envanter alanı yok.",
	["weapon_exist"] = "Zaten bu silahın sahibisin.",
	["no_weapon"] = "Bu cephane türü için silahınız yok!",
	["invalid_quantity"] = "Geçersiz miktar.",
	["item_added"] = "Eklendi:",
	["item_removed"] = "Silindi:",
	["money_added"] = "Eklendi:",
	["money_removed"] = "Silindi:",
	["weapon_added"] = "Eklendi:",
	["weapon_removed"] = "Silindi:",
	["no_money"] = "Yetersiz para",
	-- SHOP
	['shop_press_menu'] = 'Erişmek için `~INPUT_CONTEXT~` tuşuna basınız.',
    ['regular_shop_name'] = 'Mini Market',
    ['robs_liquor_name'] = 'Liquor Market',
    ['you_tool_name'] = 'Hardware Market',
   	['prison_shop_name'] = 'Cezaevi Komiseri',
	['weapon_shop_name'] = 'Silah Dükkanı',
	['license_shop_title'] = 'Lisans satın almak istiyor musun?',
	['license_shop_help'] = 'Lisans satın almak için `~INPUT_CONTEXT~` tuşuna basın.',
	['license_shop_check'] = 'Silah taşıma lisansınız zaten var!',
	['license_check_fail'] = 'Silah taşımak için lisansa ihtiyacınız var!'
}

**Comment by RuisSoftware** [comment]
Hello, you can make a pull request to add your language ;)
