### ISSUE TITLE
Script error for trunk inventory

### ISSUE THREAD

**Issue by twigmasters** [dutchplayers/FiveM-Resources#66]
I have been trying to get esx trunk inventory working and followed all the steps in the read me files. I am getting the following error...

![esx_trunk error](https://user-images.githubusercontent.com/64451461/80928599-80360200-8d73-11ea-8daf-82f02c2d2c55.png)

Any suggestions would be helpful. 

When I open my inventory with f2 I always see "secondary inventory is unavailable" as well. When pressing f3 behinf my car all it does is move slightly but if I open the trunk I can then close it with f3 which I thought was odd.

**Comment by RuisSoftware** [comment]
Why don't you use the issue template sir?

I can't do anything about it now. I just don't know why, what, IF you're doing something.

Please fill in the reproduction section before i can help.
