### ISSUE TITLE
Can't get back Items from Trunk

### ISSUE THREAD

**Issue by AntonyMax** [dutchplayers/FiveM-Resources#7]
Can't get back items in Trunk & GlowBox like Bread, Water, Materials... can take back only Weapons

**Comment by AntonyMax** [comment]
I found the Fix

Only using the newest Server Files on ESX (after 2020)

@esx_inventoryhud_trunk/server/esx_trunk-sv.lua:138
Find :
if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then

Replace to :
if targetItem.limit == nil or ((targetItem.count + count) <= targetItem.limit) then

and

@esx_inventoryhud_glovebox/server/esx_glovebox-sv.lua:138
Find :
if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then

Replace :
if targetItem.limit == nil or ((targetItem.count + count) <= targetItem.limit) then

Restart the Script or Server

**Comment by RuisSoftware** [comment]
Please try again with the new update i just released :)

**Comment by RuisSoftware** [comment]
-1 is related to items that do not have a limit. Replacing it with nil is just a quick fix to keep the code running.

**Comment by BattleStar247** [comment]
replace
if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then

with
if xPlayer.canCarryItem(item, count) then

**Comment by RuisSoftware** [comment]
just use esx 1.2 version

**Comment by BattleStar247** [comment]
i am on v1final still got this issue

**Comment by RuisSoftware** [comment]
I mean you should use our esx 1.2 version, it already have all fixes in it

**Comment by RuisSoftware** [comment]
https://github.com/dutchplayers/FiveM-Resources/tree/master/ESX/Inventory%20HUD see the 2 versions

**Comment by BattleStar247** [comment]
i tried your library.Problem is ,you add a lot of features with it.For example i like esx_shop library based system.Yours is config based. trsak version does that.
    Στις Σάββατο, 1 Μαΐου 2021, 09:22:32 μ.μ. EEST, ο χρήστης Dutch Players ***@***.***> έγραψε:  
 
 


I mean you should use our esx 1.2 version, it already have all fixes in it

**Comment by BattleStar247** [comment]
oh sorry just noticed i am on your resource post. i thought it was random inventory error. still i like your hud. but overides some of my resource like thief or esx_shops. thats why i hesitate. i    Στις Κυριακή, 2 Μαΐου 2021, 04:58:12 π.μ. EEST, ο χρήστης antonis kokosiotis ***@***.***> έγραψε:  
 
  i tried your library.Problem is ,you add a lot of features with it.For example i like esx_shop library based system.Yours is config based. trsak version does that.
    Στις Σάββατο, 1 Μαΐου 2021, 09:22:32 μ.μ. EEST, ο χρήστης Dutch Players ***@***.***> έγραψε:  
 
 


I mean you should use our esx 1.2 version, it already have all fixes in it
