### ISSUE TITLE
i team not remove from inventory 

### ISSUE THREAD

**Issue by miraz559** [dutchplayers/FiveM-Resources#73]
i used es_extended 1.1.0 with this script but its not work properly not remove item form inventory

**Comment by FiveEYZ** [comment]
as it says on the first line on the readme, this inventoryhud is updated to work with ESX 1.2

**Comment by miraz559** [comment]
you mean latest version right ?

**Comment by RuisSoftware** [comment]
We only support ESX 1.2 these days the latest version
