### ISSUE TITLE
Slow Query Warning esx_inventoryhud_trunk [956ms]

### ISSUE THREAD

**Issue by Tinky124** [dutchplayers/FiveM-Resources#79]
![1djj](https://user-images.githubusercontent.com/48660658/81400355-26e02100-912d-11ea-9d01-9134bc66c0f3.png)

**Comment by BrutalBirdie** [comment]
Please provide more information:
- how many entries does your trunk_inventory have
- when does this happen
- more context in general

**Comment by Tinky124** [comment]
1. i dont have it
2. when server started
3. on server side problem selecting everything

**Comment by BrutalBirdie** [comment]
@Tinky124 What do you mean with
> I dont have it

Do you mean you have no table in the database named `trunk_inventory`?

**Comment by Tinky124** [comment]
i have table trunk_inventory but all deleted everything in trunk_inventory and still query slow...

**Comment by BrutalBirdie** [comment]
Is your mysql server local or hosted somewhere else?
