### ISSUE TITLE
Buying process in shop doesnt work

### ISSUE THREAD

**Issue by terbaek** [dutchplayers/FiveM-Resources#80]
Can i know what this error??

SCRIPT ERROR: @esx_inventoryhud/server/main.lua:347: attempt to call a nil value (field 'canCarryItem')
SCRIPT ERROR: @esx_inventoryhud/server/main.lua:347: attempt to call a nil value (field 'canCarryItem')
SCRIPT ERROR: @esx_inventoryhud/server/main.lua:347: attempt to call a nil value (field 'canCarryItem')

**Comment by FiveEYZ** [comment]
make sure u are using latest ESX https://github.com/ESX-Org/es_extended

**Comment by terbaek** [comment]
> make sure u are using latest ESX https://github.com/ESX-Org/es_extended

already update es_extended but problem is same

**Comment by FiveEYZ** [comment]
make sure the item that is specified in config has the same name as in the database
