### ISSUE TITLE
Ammo not saving to PED

### ISSUE THREAD

**Issue by Jailmate** [dutchplayers/FiveM-Resources#83]
Issue:
- Purchase Pistol (WEAPON_PISTOL) from weapon shop with 45 rounds.
- Purchase an additional 24 rounds for the pistol (WEAPON_PISTOL_AMMO) 
- Log out, and then log back in. The weapon only has the initial 45 rounds, not the additional 24 rounds purchased.

It appears that ammo purchased from the weaponshop is not saving to the ped.

**Comment by Jailmate** [comment]
I did notice this issue registered against ESX, not sure if there is a connection between the two issues:
https://github.com/ESX-Org/es_extended/issues/715#issuecomment-619073491

**Comment by Isla-Liu** [comment]
shop ammo code should be xPlayer.addAmmo instead of AddAmmoToPed

**Comment by RuisSoftware** [comment]
Fixed with latest update
