### ISSUE TITLE
No weaponshop and no can buy license / Freeze other shop

### ISSUE THREAD

**Issue by ineokb** [dutchplayers/FiveM-Resources#84]
**Describe the bug**

When I press on buy license nothing happens without error F8 and Console and suddenly after that I can no longer go to my shop for food

**Screenshots**
https://gyazo.com/4d162dd045a0aedbf67fdcd661cfd0f4
https://gyazo.com/19fdff4f87782c2af86cdaf1dcb4d590

**ESX version:**
 - Version [e.g. 1.2]

**Followed Wiki**
Yes

**Comment by FiveEYZ** [comment]
looks like you are using a old version of esx_inventoryhud

shops now looks like this and no text in the air
![new shops](https://i.gyazo.com/41153a1189ca28491433ace6343613a4.png)
![new shops](https://i.gyazo.com/83d15108199e81e124ec531d97032e31.png)

**Comment by ineokb** [comment]
It is because I use that of ClicheUsername, and in yours there were no images thank you to you however I have this message when jre launches the server. Thx
https://gyazo.com/2f3d35fe56c5ae1129142cf0ed71dd58

**Comment by RuisSoftware** [comment]
> 
> 
> It is because I use that of ClicheUsername, and in yours there were no images thank you to you however I have this message when jre launches the server. Thx
> https://gyazo.com/2f3d35fe56c5ae1129142cf0ed71dd58

Related to https://github.com/dutchplayers/esx-inventoryhud/issues/79

Also be sure to read our Wiki
