### ISSUE TITLE
how can i disable a SHOP like which i want

### ISSUE THREAD

**Issue by heyhoung** [dutchplayers/FiveM-Resources#85]
i want to remove some of the shop in the map from this script [prison shop, bar , youtool]
these three when i only deleted the script of them , my script just not working anymore :| imma stupid i really need help

**Comment by FiveEYZ** [comment]
just comment the coord inside locations inside the config

example:
```lua
    PrisonShop = {
        Locations = {
            --{x = 1728.41, y = 2584.31, z = 45.84},
        },
        Items = {
            {name = 'bread'},
            {name = 'water'},
            {name = 'cigarette'},
            {name = 'lighter'},
            {name = 'sandwich'},
            {name = 'chips'}
        }
    },
```

**Comment by FoxeyBox** [comment]
Any ways you can disable all the shops any time I delete the files it doesn’t let me open the inventory
