### ISSUE TITLE
Slow Query Warning esx_inventoryhud_glovebox + esx_inventoryhud_trunk

### ISSUE THREAD

**Issue by Mariox6** [dutchplayers/FiveM-Resources#86]
There is no data in the tables and its fresh installed
![error](https://user-images.githubusercontent.com/48855611/81600776-7131fe00-93ca-11ea-9299-4cd16ced29f6.PNG)

**Comment by FiveEYZ** [comment]
it just means it takes time for it to run the command due to slow connection or overloaded database(maybe the server host) 

maybe something can be done in esx_inventoryhud to optimize it somehow, someone who knows more about MySQL could maybe look into it :)

edit: this basically same issue as #79
