### ISSUE TITLE
undefined item in esx_property

### ISSUE THREAD

**Issue by Mariox6** [dutchplayers/FiveM-Resources#87]
**Describe the bug**
If i put an item from my inventory in the storage, the name of the item is UNDEFINED, but if i put it back in my inventory its the normal item

**To Reproduce**
1. Go to a house and put an item in the storage

**Screenshots**
![bug](https://user-images.githubusercontent.com/48855611/81622244-bc5f0780-93f0-11ea-967a-46c05c2e554b.PNG)

**ESX version:**
 - newest es_extended version (1.2)

**Followed Wiki**
Yes

**Comment by YInfeRnal** [comment]
same
