### ISSUE TITLE
inventory problem

### ISSUE THREAD

**Issue by KOUBASGR** [dutchplayers/FiveM-Resources#9]
hello i have a problem with the inventory when i farm weed is not showing that i got +1 weed and is going to my inventory pls help

**Comment by RuisSoftware** [comment]
Hello, i will take a look in this.

**Comment by KOUBASGR** [comment]
thx

**Comment by KOUBASGR** [comment]
btw i am getting and this error as well https://prnt.sc/rv2q7s

**Comment by RuisSoftware** [comment]
Can you send the file?

**Comment by RuisSoftware** [comment]
You can try this one out for working shops with Inventoryhud: https://github.com/sukurabu/esx_inventoryhud_shops/tree/master/esx_inventoryhud

**Comment by RuisSoftware** [comment]
We use esx-kr-advanced-shops for my shops so we will not implement the shops in our inventoryhud-edit.

**Comment by KOUBASGR** [comment]
[Desktop.zip](https://github.com/dutchplayers/esx-inventoryhud/files/4447654/Desktop.zip)

**Comment by KOUBASGR** [comment]
this is my files

**Comment by RuisSoftware** [comment]
Please download the update and use all 3 resources.

**Comment by KOUBASGR** [comment]
still not showing and is giveing my that error on the console https://prnt.sc/rw8siy

**Comment by RuisSoftware** [comment]
Did you upload all sql files?

**Comment by RuisSoftware** [comment]
Check: https://github.com/dutchplayers/esx-inventoryhud/blob/master/UPLOAD%20TO%20YOUR%20DATABASE.sql

**Comment by KOUBASGR** [comment]
all the error fixed now how i can fix to show i got somthing in my invenotry example: +1 Bread
