### ISSUE TITLE
Police Job main.lua edit breaks police job?

### ISSUE THREAD

**Issue by twigmasters** [dutchplayers/FiveM-Resources#94]
I'm trying to edit the police job as instructed here...

=============================================================

## Add suport for `esx_policejob` etc...

Open `esx_policejob/client/main.lua`

Find function: OpenBodySearchMenu(player) and remove it
Add this code: 
```
function OpenBodySearchMenu(player)
	TriggerEvent("esx_inventoryhud:openPlayerInventory", GetPlayerServerId(player), GetPlayerName(player))
end
```

=============================================================

However I am not entirely clear on what this means. It says find the function and I do and delete it as instructed but below that is says add this code and it includes what I just deleted? I am a little confused and when I try to do this, the police job completely breaks.

**Followed Wiki**
yes

**Comment by RuisSoftware** [comment]
You have to delete the complete `function OpenBodySearchMenu(player)`

And after that, only add these 3 lines:
```

function OpenBodySearchMenu(player)
	TriggerEvent("esx_inventoryhud:openPlayerInventory", GetPlayerServerId(player), GetPlayerName(player))
end
```

**Comment by cyberthugig** [comment]
> You have to delete the complete `function OpenBodySearchMenu(player)`
> 
> And after that, only add these 3 lines:
> 
> ```
> 
> function OpenBodySearchMenu(player)
> 	TriggerEvent("esx_inventoryhud:openPlayerInventory", GetPlayerServerId(player), GetPlayerName(player))
> end
> ```

i have tried this it doesnt work maybe a better example
