### ISSUE TITLE
Make this work with SET_PED_DROPS_INVENTORY_WEAPON

### ISSUE THREAD

**Issue by Berkeratay** [dutchplayers/FiveM-Resources#95]
If possible :)

**Comment by Berkeratay** [comment]
@dutchplayers there a few drop weapon scripts using that native.
It drops from normal inventory but Peds can dupe the weapon using esx_inventory.

**Comment by RuisSoftware** [comment]
When i have time, ill try it out https://runtime.fivem.net/doc/natives/?_0x208A1888007FC0E6

**Comment by RuisSoftware** [comment]
Use v3
