### ISSUE TITLE
Total Weight Items Display

### ISSUE THREAD

**Issue by alexkoisine** [dutchplayers/FiveM-Resources#96]
How to display total items for each items?
Example : 1/20 of bread

![image](https://user-images.githubusercontent.com/64629964/83098266-5521a280-a0d4-11ea-9870-3c112d5b0546.png)

**Comment by FiveEYZ** [comment]
try the edits done here https://github.com/ESX-Org/es_extended/issues/632

**Comment by Rhydium** [comment]
@FiveEYZ And where do you specify the limit with that edit?

**Comment by FiveEYZ** [comment]
add back the limit column in the items table

**Comment by RuisSoftware** [comment]
This is included with inventoryhud. You need to use ESX 1.2
