### ISSUE TITLE
Cash & Black Money [BUG]

### ISSUE THREAD

**Issue by TheGreekOrder** [dutchplayers/FiveM-Resources#98]
Hello, i really like your resource and i appreciate for uploading, it is really helpful. 

I have a problem displaying money on the inventory, seems like after 100K (cash & blackmoney), the money displaying is changing into 1K and not following the correct amount on the item.

This is the examples:

- https://prnt.sc/sqo75n (Here, the output is 1.000 euros, but the real amount is 500k)
- https://prnt.sc/sqo7fa

- This also happens on both sides, i dont want you to fix it, but you can to make update for it. What i want is to tell me how i can fix it. 

Thank you!

**Comment by RuisSoftware** [comment]
We do not experience this issue. I also do not know why this happens to you.

**Comment by TheGreekOrder** [comment]
For the items, it works as it should, but it does that for the money. No idea why really. Is there anything specific i should check?

Or i can download it again to see if it still does that.

**Comment by RuisSoftware** [comment]
I am trying to reproduce it on my server, but it is working here, what are you doing exactly when it happens?

I just spawn the money

**Comment by Nosmakos97** [comment]
Well this happens after 100K amount of cash or black money, it turns it to what you saw. I dont actually remember having this but i give it with a command like /setmoney or /giveaccountmoney.

**Comment by Nosmakos97** [comment]
I tried printing, and the output was good, for some reason inserting is the issue, is there any place i can contact you to solve this faster?

**Comment by RuisSoftware** [comment]
We are available at our Discord server: https://www.dutch-players.nl/go/discord/

**Comment by SkinnyDragonCodes** [comment]
Hi I get this exact same issue, as soon as you have above 99,999 in cash on you the cash in the inventory shows as 1,000. You still have the 100k on you but it does not let you buy a property for instance for 25,000 as it technically registers as 1,000 but the database shows as 100,000.

**Comment by SkinnyDragonCodes** [comment]
I have a fix for this: 

 **function formatMoney(number) {

  return number.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

(dont need this but it prints in console)console.log(formatMoney(10000));   // $10,000.00
(dont need this but it prints in console)console.log(formatMoney(1000000)); // $1,000,000.00**

If you add this into the inventory.js and replace the existing "formatmoney" function it will display as you need it to. You can set yours to your currency that you need, mine is set to GBP and it works fine :) 

![image](https://user-images.githubusercontent.com/62304200/88923580-da0e7100-d269-11ea-97c9-9a38d38e9b05.png)

**Comment by Nosmakos** [comment]
For some reason it doesnt work, i get an error on this and the money dont even display on inventory(not even item).

**Comment by RuisSoftware** [comment]
Merged :)
